package calculat.CALCULAT.ProcedureSteps;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//             Servlet Manager Source Code Generated by
//                            CA Gen 8.6
//
//     Copyright (c) 2017 CA Technologies. All rights reserved.
//
//    Model Name:  CALCULAT
//
//    Load Mod:    CALCULAT                  Date: 17/04/09
//    Target OS:   JVM                       Time: 22:59:12
//    Target DBMS: JDBC                      User: mansour
//    Target GUI:  INTERNET                 
//    Dialect:     Default                  
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.reflect.*;
import java.util.*;
import java.io.*;
import java.math.*;
import com.ca.gen.smrt.*;
import com.ca.gen.smrt.controls.*;
import com.ca.gen.smrt.events.*;
import com.ca.gen.fmrt.*;
import com.ca.gen.wmrt.*;
import com.ca.gen.wmrt.controls.*;
import com.ca.gen.wmrt.controls.listboxsupport.*;
import com.ca.gen.wmrt.commands.*;
import com.ca.gen.wmrt.events.*;
import com.ca.gen.wmrt.editpatterns.*;
import com.ca.gen.abrt.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.odc.*;

import com.ca.gen.csu.exception.*;

public class CALCULAT_WIN extends ServletProcedureStep
{
  private static Boolean isFirstProcedureStep = Boolean.FALSE;
  private static String clearScreenTranCode = "CALCULA1";
  private static List supportedNames = new ArrayList();
  private static List sAvailableWindows = new ArrayList();
  
  static {
    sAvailableWindows.add("CALCULAT_WIN");
  }
  
  public static List getAvailableWindows() { 
      return sAvailableWindows; 
  } 
  
  @Override public void initAvailableWindows()
  {
      availableWindows.addAll(sAvailableWindows); 
  }
  
  static {
    supportedNames.add("CALCULAT_WIN");
    supportedNames.add("CALCULAT_WIN");
  }
  
  public static List getSupportedNames()
  {
    return(supportedNames);
  }
  
  public static String getClearScreenTranCode()
  {
    return(clearScreenTranCode);
  }
  
  @Override public final void initProximity()
  {
    proximity = DialogFlowDefinition.INTERNAL;
  }
  
  public final int getProximity()
  {
     return DialogFlowDefinition.INTERNAL;
  }
  
  public static Boolean isFirstProcedureStep()
  	throws CSUException
  {
    return(Boolean.FALSE);
  }
  
  @Override public final String getName()
  {
    return("CALCULAT_WIN");
  }
  
  @Override protected final void initName()
  {
    name = "CALCULAT_WIN";
  }
  
  @Override public final String getActionBlockName()
  {
    return("calculat.HOME");
  }
  
  @Override public final void initActionBlockName()
  {
    actionBlockName = "calculat.HOME";
  }
  
  @Override protected final void initImportView()
  {
    importView = new calculat.HOME_IA();
  }
  
  public final IImportView getNewImportView()
  {
    return(new calculat.HOME_IA());
  }
  
  @Override protected final void initExportView()
  {
    exportView = new calculat.HOME_OA();
  }
  
  public final IExportView getNewExportView()
  {
    return(new calculat.HOME_OA());
  }
  
  @Override protected final String getFlowDefinitionsClassName(String lowerDialectNameDot)
  {
    return("calculat."+lowerDialectNameDot+"CALCULAT.FlowTables.CALCULAT_WIN");
  }
  
  @Override public final void inout_viewmap(IImportView ia, IExportView oa)
  {
    // Input to output View Mapping function
    INOUT_3C00001_CALCULAT_WIN((calculat.HOME_IA)ia,
          (calculat.HOME_OA)oa);
  }
  
  @Override public final void outin_viewmap(IImportView ia, IExportView oa)
  {
    // Output to input View Mapping function
    OUTIN_3C00001_CALCULAT_WIN((calculat.HOME_IA)ia,
          (calculat.HOME_OA)oa);
  }
  
  
  public final static void INOUT_3C00001_CALCULAT_WIN(calculat.HOME_IA ia, calculat.HOME_OA oa)
  {
    // copy mapped fields from w-ia to w-oa for display 1st
    // dialog flows either display 1st flows on or display 1st
    // returns on
    
    oa.ExportResultIefSuppliedResult = IntAttr.valueOf(ia.ImportResultIefSuppliedResult);
    oa.ExportN1IefSuppliedNumber1st = IntAttr.valueOf(ia.ImportN1IefSuppliedNumber1st);
    oa.ExportN2ndIefSuppliedNumber2 = IntAttr.valueOf(ia.ImportN2ndIefSuppliedNumber2);
  }
  
  public final static void OUTIN_3C00001_CALCULAT_WIN(calculat.HOME_IA ia, calculat.HOME_OA oa)
  {
    // copy mapped fields from w-oa to w-ia.  Called by
    // win_in & dlg_in functions to populate import view
    // before accepting window's fields
    
    ia.ImportResultIefSuppliedResult = IntAttr.valueOf(oa.ExportResultIefSuppliedResult);
    ia.ImportN1IefSuppliedNumber1st = IntAttr.valueOf(oa.ExportN1IefSuppliedNumber1st);
    ia.ImportN2ndIefSuppliedNumber2 = IntAttr.valueOf(oa.ExportN2ndIefSuppliedNumber2);
  }
  
  @Override public void mapImportView(String type, ProcedureStep pStep)
  {
    if ( type == null )
    {
      // no-op
    }
    else if ( type.equals( "FSEND_E400002_DLGFLOW" ) )
    {
      CALCULAT_WIN.FSEND_E400002_DLGFLOW((calculat.EXPERT_IA)pStep.getImportView(), (calculat.HOME_OA)getExportView());
    }
    else if ( type.equals( "FRTRN_E400002_DLGFLOW" ) )
    {
      CALCULAT_WIN.FRTRN_E400002_DLGFLOW((calculat.HOME_OA)getExportView(), (calculat.HOME_IA)getImportView(), (calculat.EXPERT_OA)
        pStep.getExportView());
    }
  }
  
  public final static void FSEND_E400002_DLGFLOW(calculat.EXPERT_IA ia, calculat.HOME_OA oa)
  {
    int gv1_hole = 0;
    int adim1 = 0;
    // copy dialog flow mapped w-oa fields to w-ia
    ia.InResultIefSuppliedResult = IntAttr.valueOf(oa.ExportResultIefSuppliedResult);
    ia.ImportAmatyListAmatyDropList1 = FixedStringAttr.valueOf(oa.ImportAmatyListAmatyDropList1, (short)1);
  }
  
  public final static void FRTRN_E400002_DLGFLOW(calculat.HOME_OA prev_oa, calculat.HOME_IA ia, calculat.EXPERT_OA rtrn_oa)
  {
    int gv1_hole = 0;
    int adim1 = 0;
    // if field not in returns on view matching
    // copy prev export view item to import view
    // based on mapping assoc to flows on pstep
    //
    
    OUTIN_3C00001_CALCULAT_WIN(ia, prev_oa);
    
    // if field in returns on view matching
    // copy returned export view item to import view
    // if field in view match call getRecieveBuffer
    // else call skipReceiveBuffer
    ia.ImportResultIefSuppliedResult = IntAttr.valueOf(rtrn_oa.OutResultIefSuppliedResult);
  }
}
