package calculat.CALCULAT.FlowTables;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//             Servlet Manager Source Code Generated by
//                            CA Gen 8.6
//
//     Copyright (c) 2017 CA Technologies. All rights reserved.
//
//    Model Name:  CALCULAT
//
//    Load Mod:    CALCULAT                  Date: 17/04/09
//    Target OS:   JVM                       Time: 22:59:12
//    Target DBMS: JDBC                      User: mansour
//    Target GUI:  INTERNET                 
//    Dialect:     Default                  
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.reflect.*;
import java.util.*;
import java.io.*;
import java.math.*;
import com.ca.gen.smrt.*;
import com.ca.gen.smrt.controls.*;
import com.ca.gen.smrt.events.*;
import com.ca.gen.fmrt.*;
import com.ca.gen.wmrt.*;
import com.ca.gen.wmrt.controls.*;
import com.ca.gen.wmrt.controls.listboxsupport.*;
import com.ca.gen.wmrt.commands.*;
import com.ca.gen.wmrt.events.*;
import com.ca.gen.wmrt.editpatterns.*;
import com.ca.gen.abrt.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.odc.*;

          /********************************************************/
          /*  Flow Tables for Business Process Step CALCULAT_WIN  */
          /********************************************************/

public class CALCULAT_WIN implements IFlowDefinitions
{
  final static ExitState RO_E400002_DLGFLOW[] = {
    new ExitState(238026768, null, ExitState.NORMAL)
  };
  
  /* defines properties of a dialog flow */
  public final static DialogFlowDefinition flowDefinitions [] =
  {
    new DialogFlowDefinition(
        new ExitState(238026769, null, ExitState.NORMAL),
        null,
        null,
        DialogFlowDefinition.EXECUTE_FIRST,    // Execute first on flow
        "FSEND_E400002_DLGFLOW",    /* import view map, data sent */
        null,   // Do not send a command on Flow
        false,         // Don't send current exit state
        RO_E400002_DLGFLOW,
        null,
        null,
        DialogFlowDefinition.EXECUTE_FIRST,    /* Execute first on return */
        "FRTRN_E400002_DLGFLOW",    /* export view map, data returned */
        null,   // Do not send a command on Return
        true,          // Return current exit state
        DialogFlowDefinition.LINK,    // Flow type
        DialogFlowDefinition.INTERNAL,
        "calculat.CALCULAT.ProcedureSteps.AMATY"
    )
  };
  
  public DialogFlowDefinition [] getDialogFlows()
  {
    return(flowDefinitions);
  }
  
  public CALCULAT_WIN()
      {
    ;
      }
  
} // End of CALCULAT_WIN class 
