/****************************************************************
 *
 *             Window Manager Source Code Generated by
 *                           CA Gen 8.6
 *
 *    Copyright (c) 2017 CA Technologies. All rights reserved.
 *
 *    Model Name:  CALCULAT
 *
 *    Load Mod:    CAL                       Date: 17/04/09
 *    Target OS:   WINDOWS                   Time: 21:24:06
 *    Target DBMS: <NONE>                    User: mansour
 *    Target GUI:  WINDOWS                  
 *    Dialect:     Default                  
 *
 ***************************************************************/
#define  WINDOW_MANAGER_CFILE
#define  ADVANTAGE_GEN_APPLICATION
#define  GEN_VERSION 8600333
#include "wgr.h"
#include "tirdpproto.h"
#include "CAL.h"
/* * * * * * * * * * * * * * * * * * * * */
/* START OF IMPORT VIEWS */
/* * * * * * * * * * * * * * * * * * * * */
/* Data View Group: w_ia */
/*  DVG id name: a_0105906284_ia */
typedef struct
{
/* Entity View: IMPORT_RESULT (import_result_001ev) */
/*        Type: IEF_SUPPLIED (ief_supplied_001et) */
char result_001as;
long result_001;
/* Entity View: IMPORT_N2ND (import_n2nd_002ev) */
/*        Type: IEF_SUPPLIED (ief_supplied_002et) */
char number2_002as;
long number2_002;
/* Entity View: IMPORT_N1 (import_n1_003ev) */
/*        Type: IEF_SUPPLIED (ief_supplied_003et) */
char number1st_003as;
long number1st_003;
} a_0105906284_ia;
/* Data View Group: w_ia */
/*  DVG id name: a_0105906281_ia */
typedef struct
{
/* Entity View: IMPORT_AMATY_LIST (import_amaty_list_004ev) */
/*        Type: AMATY (amaty_004et) */
char drop_list1_004as;
char drop_list1_004[2] /* 1 + 1 */;
/* Entity View: IN_DEMO_TEXT (in_demo_text_005ev) */
/*        Type: DEMO_TEXT_1111 (demo_text_1111_005et) */
char text1111_005as;
char text1111_005[101] /* 100 + 1 */;
/* Entity View: IN_RESULT (in_result_006ev) */
/*        Type: IEF_SUPPLIED (ief_supplied_006et) */
char result_006as;
long result_006;
/* Entity View: IN_N1 (in_n1_007ev) */
/*        Type: IEF_SUPPLIED (ief_supplied_007et) */
char total_real_007as;
double total_real_007;
} a_0105906281_ia;
/* * * * * * * * * * * * * * * * * * * * */
/* START OF EXPORT VIEWS */
/* * * * * * * * * * * * * * * * * * * * */
/* Data View Group: w_oa */
/*  DVG id name: a_0106954861_oa */
typedef struct
{
/* Entity View: EXPORT_RESULT (export_result_008ev) */
/*        Type: IEF_SUPPLIED (ief_supplied_008et) */
char result_008as;
char result_008at[6];
long result_008;
/* Entity View: EXPORT_N2ND (export_n2nd_009ev) */
/*        Type: IEF_SUPPLIED (ief_supplied_009et) */
char number2_009as;
char number2_009at[6];
long number2_009;
/* Entity View: EXPORT_N1 (export_n1_010ev) */
/*        Type: IEF_SUPPLIED (ief_supplied_010et) */
char number1st_010as;
char number1st_010at[6];
long number1st_010;
} a_0106954861_oa;
/* Data View Group: w_oa */
/*  DVG id name: a_0106954858_oa */
typedef struct
{
/* Entity View: EXPORT_AMATY (export_amaty_011ev) */
/*        Type: AMATY (amaty_011et) */
char drop_list1_011as;
char drop_list1_011at[6];
char drop_list1_011[2] /* 1 + 1 */;
/* Entity View: OUT_DEMO_TEXT (out_demo_text_012ev) */
/*        Type: DEMO_TEXT_1111 (demo_text_1111_012et) */
char text1111_012as;
char text1111_012at[6];
char text1111_012[101] /* 100 + 1 */;
/* Entity View: OUT_RESULT (out_result_013ev) */
/*        Type: IEF_SUPPLIED (ief_supplied_013et) */
char result_013as;
char result_013at[6];
long result_013;
/* Entity View: OUT_N1 (out_n1_014ev) */
/*        Type: IEF_SUPPLIED (ief_supplied_014et) */
char total_real_014as;
char total_real_014at[6];
double total_real_014;
/* Entity View: OUT_TITLE_ALL (out_title_all_015ev) */
/*        Type: CALCULAT_NAME (calculat_name_015et) */
char alllllll_015as;
char alllllll_015at[6];
char alllllll_015[201] /* 200 + 1 */;
} a_0106954858_oa;
/* * * * * * * * * * * * * * * * * * * * */
/* PERMITTED VALUE TABLES */
/* * * * * * * * * * * * * * * * * * * * */
static WIPERMIT PVAL_3600074_FLAG[] =
    {
    {"N", NULL},
    {"Y", NULL},
    {0, 0}
    };

static WIPERMIT PVAL_360009F_DROP_LIST1[] =
    {
    {"+", NULL},
    {"-", NULL},
    {"E", NULL},
    {"D", NULL},
    {0, 0}
    };


#define TGT_GLOBDATA 
#include <tiabglob.h>
static GLOBDATA glob_data; 

 
static short adim1 = 0;
static short adim2 = 0;
static short adim3 = 0;
static char  data_present = 'Y';
static char  active_entry = 'Y';

          /********************************************************/
          /*  Flow Tables for Business Process Step CALCULAT_WIN  */
          /********************************************************/

/* maps from command identifer to exit state identifer */
static AUTOFLOW AF_3C00001_CALCULAT_WIN [] =
    {
    0,0
    };    /* nulls terminate list of autoflow maps */

/* maps exit state to dialog flows */
static EXITSTATEUSAGE ES_3C00001_CALCULAT_WIN [] =
    {
    238026769,    /* exitstate object id (RETURN_BACK_TO_EXPERT_AMATY) */
    239075330,    /* dialogflow object id to invoke */
    'M',    /* termination action */
    0,    /* string resource id containing msg text*/
    0,0
    };    /* nulls terminate list of exit state maps */

/* defines returns on commands and exit states */
static RETURNSON RO_E400002_DLGFLOW [] =
    {
    0,    /* command resource id received */
    NULL, /* command text */
    238026768,    /* exitstate object id */
    0,0,0
    };    /* nulls terminate list of returns on */


            /*****************************************************/
            /*  Dialog flow view mapping: Function Declarations  */
            /*****************************************************/

void FSEND_E400002_DLGFLOW(a_0105906281_ia *ia,a_0106954861_oa *oa)
;
void FRTRN_E400002_DLGFLOW(a_0106954861_oa *prev_oa,a_0105906284_ia *ia,a_0106954858_oa *rtrn_oa)
;
/* defines properties of a dialog flow */
static DIALOGFLOW DF_3C00001_CALCULAT_WIN [] =
    {
    239075330,    /* dialog flow object id */
    DF_LINK,    /* dialog flow type */
    PID_3C00000_AMATY,    /* procedure resource id flowed to */
    "AMATY",    /* procedure name flowed to */
    &FSEND_E400002_DLGFLOW,    /* import view map, data sent */
    &FRTRN_E400002_DLGFLOW,    /* export view map, data returned */
    RO_E400002_DLGFLOW,    /* returns on table */
    DF_EXEC1ST,    /* display or exec 1st flow */
    NULL,
    DR_EXEC1ST,    /* display or exec 1st flow */
    NULL,
    FALSE,         /* send current exit state? */
    TRUE,          /* return current exit state? */
    0,0,0
    };    /* nulls terminate list of dialog flows */


              /*************************************************/
              /*  Flow Tables for Business Process Step AMATY  */
              /*************************************************/

/* No flows exist for this pstep */

                         /***************************/
                         /*  Function Declarations  */
                         /***************************/

extern void HOME(char *,char *,void *,void *,void *)
;
extern void home_calculat_na_pb_click01(char *,char *,void *,void *,void *)
;
extern void home_calculat_na_pb_clear_cli02(char *,char *,void *,void *,void *)
;
extern void home_calculat_min_pb_click03(char *,char *,void *,void *,void *)
;
extern void home_calculat_wi_pb_multip_cl04(char *,char *,void *,void *,void *)
;
extern void home_calculat_wi_pb_amaty_cli05(char *,char *,void *,void *,void *)
;
void INOUT_3C00001_CALCULAT_WIN(a_0105906284_ia *,a_0106954861_oa *)
;
void OUTIN_3C00001_CALCULAT_WIN(a_0105906284_ia *,a_0106954861_oa *)
;
void XRECV_3C00001_CALCULAT_WIN(a_0105906284_ia *,char *)
;
void XRTRN_3C00001_CALCULAT_WIN(a_0106954861_oa *,char *)
;
void win_IN_12700000_CALCULAT_WIN(void *,a_0105906284_ia *,a_0106954861_oa *)
;
void win_OUT_12700000_CALCULAT_WIN(void *,a_0106954861_oa *)
;
extern void EXPERT(char *,char *,void *,void *,void *)
;
extern void expert_amaty_pb_plus_click01(char *,char *,void *,void *,void *)
;
extern void expert_amaty_pb_mine_click02(char *,char *,void *,void *,void *)
;
extern void expert_amaty_pb_clear_click03(char *,char *,void *,void *,void *)
;
extern void expert_amaty_pb_back_click04(char *,char *,void *,void *,void *)
;
extern void expert_amaty_pb_1_click05(char *,char *,void *,void *,void *)
;
extern void expert_amaty_pb_2_click06(char *,char *,void *,void *,void *)
;
extern void expert_amaty_pb_3_click07(char *,char *,void *,void *,void *)
;
extern void expert_amaty_pb_4_click08(char *,char *,void *,void *,void *)
;
extern void expert_amaty_pb_5_click09(char *,char *,void *,void *,void *)
;
extern void expert_amaty_pb_6_click10(char *,char *,void *,void *,void *)
;
extern void expert_amaty_pb_7_click11(char *,char *,void *,void *,void *)
;
extern void expert_amaty_pb_8_click12(char *,char *,void *,void *,void *)
;
extern void expert_amaty_pb_9_click13(char *,char *,void *,void *,void *)
;
extern void expert_amaty_pb_0_click14(char *,char *,void *,void *,void *)
;
extern void expert_amaty_pb_ok_click15(char *,char *,void *,void *,void *)
;
extern void expert_always_move_list_chang16(char *,char *,void *,void *,void *)
;
extern void expert_amaty_dl_drop_list1_ch17(char *,char *,void *,void *,void *)
;
void INOUT_3C00000_AMATY(a_0105906281_ia *,a_0106954858_oa *)
;
void OUTIN_3C00000_AMATY(a_0105906281_ia *,a_0106954858_oa *)
;
void XRECV_3C00000_AMATY(a_0105906281_ia *,char *)
;
void XRTRN_3C00000_AMATY(a_0106954858_oa *,char *)
;
void win_IN_12700001_AMATY(void *,a_0105906281_ia *,a_0106954858_oa *)
;
void win_OUT_12700001_AMATY(void *,a_0106954858_oa *)
;
                        /****************************/
                        /*  Pstep Usage Prototypes  */
                        /****************************/
                           /**********************/
                           /*  Check and Ignore  */
                           /**********************/
void CHECK_OR_IGNORE_ASYNC_RESPONSE(char *,char *,char *,char *,char *)
;
                      /*********************************/
                      /*  enable/disable state tables  */
                      /*********************************/
                   /**************************************/
                   /*  Button lists and Fldgroup tables  */
                   /**************************************/
static WIDOMAIN UID_11F00005_NUMBER1ST =
    {
    8,
    BT_LONG,
    8,
    0,
    "",
    NULL,
    FALSE,
    FALSE,
    NULL
    };

static WIFLDEDIT UIFG_11F00005_NUMBER1ST =
    {
    WI_PS_SNGLLINE_EDIT, /* edit style */ 
    &UID_11F00005_NUMBER1ST    /* domain */
    };

static WIFLDCMDBTN UIFG_11000000_PLUS =
    {
    WI_PS_COMMAND_BUTTON  /* pres style */
    };

static WIFLDCMDBTN UIFG_11000002_MINS =
    {
    WI_PS_COMMAND_BUTTON  /* pres style */
    };

static WIDOMAIN UID_11F00003_NUMBER2 =
    {
    5,
    BT_LONG,
    5,
    0,
    "",
    NULL,
    FALSE,
    FALSE,
    NULL
    };

static WIFLDEDIT UIFG_11F00003_NUMBER2 =
    {
    WI_PS_SNGLLINE_EDIT, /* edit style */ 
    &UID_11F00003_NUMBER2    /* domain */
    };

static WIFLDCMDBTN UIFG_11000006_NO_COMMAND =
    {
    WI_PS_COMMAND_BUTTON  /* pres style */
    };

static WIDOMAIN UID_11F00007_RESULT =
    {
    8,
    BT_LONG,
    8,
    0,
    "",
    NULL,
    FALSE,
    FALSE,
    NULL
    };

static WIFLDEDIT UIFG_11F00007_RESULT =
    {
    WI_PS_SNGLLINE_READONLY, /* readonly style */ 
    &UID_11F00007_RESULT    /* domain */
    };

static WIFLDCMDBTN UIFG_1100000A_NO_COMMAND =
    {
    WI_PS_COMMAND_BUTTON  /* pres style */
    };

static WIFLDCMDBTN UIFG_11000009_CLEAR =
    {
    WI_PS_COMMAND_BUTTON  /* pres style */
    };

                          /*************************/
                          /*  Reparenting structs  */
                          /*************************/
                        /*****************************/
                        /*  Panel Field Definitions  */
                        /*****************************/

static WIFIELD UIF_12700000_CALCULAT_WIN[]
    WI_BEGIN_FIELD_LIST
    {
    RCID_11F00005_NUMBER1ST,    /* resource identifier */
    &UIFG_11F00005_NUMBER1ST,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    RCLT_11F00005_NUMBER1ST,     /* prompt's resource id */
    "Number1",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCMD_11000000_PLUS,    /* resource identifier */
    &UIFG_11000000_PLUS,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    0,     /* prompt's resource id */
    "plus",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCMD_11000002_MINS,    /* resource identifier */
    &UIFG_11000002_MINS,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    0,     /* prompt's resource id */
    "mins",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCID_11F00003_NUMBER2,    /* resource identifier */
    &UIFG_11F00003_NUMBER2,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    RCLT_11F00003_NUMBER2,     /* prompt's resource id */
    "Number2",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCMD_11000006_NO_COMMAND,    /* resource identifier */
    &UIFG_11000006_NO_COMMAND,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    0,     /* prompt's resource id */
    "multiply",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCID_11F00007_RESULT,    /* resource identifier */
    &UIFG_11F00007_RESULT,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    RCLT_11F00007_RESULT,     /* prompt's resource id */
    "Field1",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCMD_1100000A_NO_COMMAND,    /* resource identifier */
    &UIFG_1100000A_NO_COMMAND,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    0,     /* prompt's resource id */
    "Amaty",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCMD_11000009_CLEAR,    /* resource identifier */
    &UIFG_11000009_CLEAR,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    0,     /* prompt's resource id */
    "Button1",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    WI_END_FIELD_LIST;

static WILITERAL LTBL_12700000_CALCULAT_WIN[] = 
    {
    { 0, 0, 0 }
    };

                       /******************************/
                       /*  Command Table for Window  */
                       /******************************/
static WICOMMAND UIC_12700000_CALCULAT_WIN[]
    WI_BEGIN_CMD_LIST
    {RCMD_11000000_PLUS,"PLUS",CM_OTHER,NULL,0,RCMD_E10000F_PLUS,ST_PUSHBUTTON,DEFAULT_STATUS, "plus"},
    {RCMD_11000002_MINS,"MINS",CM_OTHER,NULL,0,RCMD_E100010_MINS,ST_PUSHBUTTON,DEFAULT_STATUS, "mins"},
    {RCMD_11000006_NO_COMMAND,"",CM_OTHER,NULL,0,0,ST_PUSHBUTTON,DEFAULT_STATUS, "multiply"},
    {RCMD_1100000A_NO_COMMAND,"",CM_OTHER,NULL,0,0,ST_PUSHBUTTON,DEFAULT_STATUS, "Amaty"},
    {RCMD_11000009_CLEAR,"CLEAR",CM_OTHER,NULL,0,RCMD_E100004_CLEAR,ST_PUSHBUTTON,DEFAULT_STATUS, "Button1"},
    WI_END_CMD_LIST;

                        /****************************/
                        /*  Event Table for Window  */
                        /****************************/
static WIEVENT EVT_12700000_CALCULAT_WIN[]
    WI_BEGIN_EVENT_LIST
    {RCMD_11000000_PLUS,    /* resource id of the control */
        "Click",    /* event type */
        home_calculat_na_pb_click01,    /* event handler */
        0,    /* command */
        ' ',    /* map flag */
        0,    /* OLE event flag */
        0,    /* offset of return attribute */
        0,    /* length of return attribute */
        0,    /* datatype of return attribute */
        0},    /* decimals for return value */
    {RCMD_11000002_MINS,    /* resource id of the control */
        "Click",    /* event type */
        home_calculat_min_pb_click03,    /* event handler */
        0,    /* command */
        ' ',    /* map flag */
        0,    /* OLE event flag */
        0,    /* offset of return attribute */
        0,    /* length of return attribute */
        0,    /* datatype of return attribute */
        0},    /* decimals for return value */
    {RCMD_11000006_NO_COMMAND,    /* resource id of the control */
        "Click",    /* event type */
        home_calculat_wi_pb_multip_cl04,    /* event handler */
        0,    /* command */
        ' ',    /* map flag */
        0,    /* OLE event flag */
        0,    /* offset of return attribute */
        0,    /* length of return attribute */
        0,    /* datatype of return attribute */
        0},    /* decimals for return value */
    {RCMD_1100000A_NO_COMMAND,    /* resource id of the control */
        "Click",    /* event type */
        home_calculat_wi_pb_amaty_cli05,    /* event handler */
        0,    /* command */
        ' ',    /* map flag */
        0,    /* OLE event flag */
        0,    /* offset of return attribute */
        0,    /* length of return attribute */
        0,    /* datatype of return attribute */
        0},    /* decimals for return value */
    {RCMD_11000009_CLEAR,    /* resource id of the control */
        "Click",    /* event type */
        home_calculat_na_pb_clear_cli02,    /* event handler */
        0,    /* command */
        ' ',    /* map flag */
        0,    /* OLE event flag */
        0,    /* offset of return attribute */
        0,    /* length of return attribute */
        0,    /* datatype of return attribute */
        0},    /* decimals for return value */
    WI_END_EVENT_LIST;

                      /********************************/
                      /*  Menu Merge Info for Window  */
                      /********************************/
static MENUMERGE MM_12700000_CALCULAT_WIN[] =
    {0,0,0};
                      /*********************************/
                      /*  enable/disable state tables  */
                      /*********************************/
                   /**************************************/
                   /*  Button lists and Fldgroup tables  */
                   /**************************************/
static WIDOMAIN UID_11F00013_ALLLLLLL =
    {
    200,
    BT_STRING,
    200,
    0,
    "",
    NULL,
    FALSE,
    TRUE,
    NULL
    };

static WIFLDEDIT UIFG_11F00013_ALLLLLLL =
    {
    WI_PS_SNGLLINE_READONLY, /* readonly style */ 
    &UID_11F00013_ALLLLLLL    /* domain */
    };

static WIDOMAIN UID_11F00017_RESULT =
    {
    8,
    BT_LONG,
    8,
    0,
    "",
    NULL,
    FALSE,
    FALSE,
    NULL
    };

static WIFLDEDIT UIFG_11F00017_RESULT =
    {
    WI_PS_SNGLLINE_READONLY, /* readonly style */ 
    &UID_11F00017_RESULT    /* domain */
    };

static WIDOMAIN UID_11F00015_TOTAL_REAL =
    {
    8,
    BT_DOUBLE,
    17,
    0,
    "ZZZZZZZZ",
    NULL,
    FALSE,
    FALSE,
    NULL
    };

static WIFLDEDIT UIFG_11F00015_TOTAL_REAL =
    {
    WI_PS_SNGLLINE_EDIT, /* edit style */ 
    &UID_11F00015_TOTAL_REAL    /* domain */
    };

static WIFLDCMDBTN UIFG_1100000F_NO_COMMAND =
    {
    WI_PS_COMMAND_BUTTON  /* pres style */
    };

static WIFLDCMDBTN UIFG_1100000E_NO_COMMAND =
    {
    WI_PS_COMMAND_BUTTON  /* pres style */
    };

static WIFLDCMDBTN UIFG_11000012_NO_COMMAND =
    {
    WI_PS_COMMAND_BUTTON  /* pres style */
    };

static WIBUTTON PSB_F700016_DROP_LIST1[]
    WI_BEGIN_BUTTON_LIST
    {RCID_F600006_DROP_LIST1,1,1,NULL,NULL},
    {RCID_F600002_DROP_LIST1,2,0,NULL,NULL},
    {RCID_F600005_DROP_LIST1,3,0,NULL,NULL},
    WI_END_BUTTON_LIST;

static char *VALS_F700016_DROP_LIST1[] =
    {
    "E",
    "+",
    "-",
    "D",
    0
    };

static BUTTONEDIT WIED_F700016_DROP_LIST1 =
    {
    VALS_F700016_DROP_LIST1, BT_STRING, 1, 0, "", TRUE
    };

static WIFLDGROUP UIFG_F700016_DROP_LIST1 =
    {
    WI_PS_PERMVALUE_LIST, PSB_F700016_DROP_LIST1, &WIED_F700016_DROP_LIST1
    };

static WIFLDCMDBTN UIFG_1100001E_ENTER =
    {
    WI_PS_COMMAND_BUTTON  /* pres style */
    };

static WIFLDCMDBTN UIFG_11000011_NO_COMMAND =
    {
    WI_PS_COMMAND_BUTTON  /* pres style */
    };

static WIFLDCMDBTN UIFG_11000010_NO_COMMAND =
    {
    WI_PS_COMMAND_BUTTON  /* pres style */
    };

static WIFLDCMDBTN UIFG_11000014_NO_COMMAND =
    {
    WI_PS_COMMAND_BUTTON  /* pres style */
    };

static WIFLDCMDBTN UIFG_11000019_NO_COMMAND =
    {
    WI_PS_COMMAND_BUTTON  /* pres style */
    };

static WIFLDCMDBTN UIFG_1100001A_NO_COMMAND =
    {
    WI_PS_COMMAND_BUTTON  /* pres style */
    };

static WIFLDCMDBTN UIFG_1100001B_NO_COMMAND =
    {
    WI_PS_COMMAND_BUTTON  /* pres style */
    };

static WIFLDCMDBTN UIFG_1100001D_NO_COMMAND =
    {
    WI_PS_COMMAND_BUTTON  /* pres style */
    };

static WIFLDCMDBTN UIFG_1100000B_PLUS =
    {
    WI_PS_COMMAND_BUTTON  /* pres style */
    };

static WIFLDCMDBTN UIFG_1100001F_MINS =
    {
    WI_PS_COMMAND_BUTTON  /* pres style */
    };

static WIFLDCMDBTN UIFG_1100000D_RETURN =
    {
    WI_PS_COMMAND_BUTTON  /* pres style */
    };

static WIFLDCMDBTN UIFG_1100000C_NO_COMMAND =
    {
    WI_PS_COMMAND_BUTTON  /* pres style */
    };

static WIDOMAIN UID_11F00008_TEXT1111 =
    {
    100,
    BT_STRING,
    100,
    0,
    "",
    NULL,
    FALSE,
    TRUE,
    NULL
    };

static WIFLDEDIT UIFG_11F00008_TEXT1111 =
    {
    WI_PS_SNGLLINE_EDIT, /* edit style */ 
    &UID_11F00008_TEXT1111    /* domain */
    };

                          /*************************/
                          /*  Reparenting structs  */
                          /*************************/
                        /*****************************/
                        /*  Panel Field Definitions  */
                        /*****************************/

static WIFIELD UIF_12700001_AMATY[]
    WI_BEGIN_FIELD_LIST
    {
    RCID_11F00013_ALLLLLLL,    /* resource identifier */
    &UIFG_11F00013_ALLLLLLL,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    RCLT_11F00013_ALLLLLLL,     /* prompt's resource id */
    "Field1",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCID_11F00017_RESULT,    /* resource identifier */
    &UIFG_11F00017_RESULT,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    RCLT_11F00017_RESULT,     /* prompt's resource id */
    "Field3",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCID_11F00015_TOTAL_REAL,    /* resource identifier */
    &UIFG_11F00015_TOTAL_REAL,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    RCLT_11F00015_TOTAL_REAL,     /* prompt's resource id */
    "Field2",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCMD_1100000F_NO_COMMAND,    /* resource identifier */
    &UIFG_1100000F_NO_COMMAND,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    0,     /* prompt's resource id */
    "Button3",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCMD_1100000E_NO_COMMAND,    /* resource identifier */
    &UIFG_1100000E_NO_COMMAND,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    0,     /* prompt's resource id */
    "Button4",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCMD_11000012_NO_COMMAND,    /* resource identifier */
    &UIFG_11000012_NO_COMMAND,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    0,     /* prompt's resource id */
    "Button5",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCID_F700016_DROP_LIST1,    /* resource identifier */
    &UIFG_F700016_DROP_LIST1,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    RCLT_F700016_DROP_LIST1,     /* prompt's resource id */
    "DropDownList1",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCMD_1100001E_ENTER,    /* resource identifier */
    &UIFG_1100001E_ENTER,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    0,     /* prompt's resource id */
    "Button14",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCMD_11000011_NO_COMMAND,    /* resource identifier */
    &UIFG_11000011_NO_COMMAND,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    0,     /* prompt's resource id */
    "Button6",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCMD_11000010_NO_COMMAND,    /* resource identifier */
    &UIFG_11000010_NO_COMMAND,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    0,     /* prompt's resource id */
    "Button7",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCMD_11000014_NO_COMMAND,    /* resource identifier */
    &UIFG_11000014_NO_COMMAND,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    0,     /* prompt's resource id */
    "Button8",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCMD_11000019_NO_COMMAND,    /* resource identifier */
    &UIFG_11000019_NO_COMMAND,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    0,     /* prompt's resource id */
    "Button9",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCMD_1100001A_NO_COMMAND,    /* resource identifier */
    &UIFG_1100001A_NO_COMMAND,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    0,     /* prompt's resource id */
    "Button10",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCMD_1100001B_NO_COMMAND,    /* resource identifier */
    &UIFG_1100001B_NO_COMMAND,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    0,     /* prompt's resource id */
    "Button11",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCMD_1100001D_NO_COMMAND,    /* resource identifier */
    &UIFG_1100001D_NO_COMMAND,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    0,     /* prompt's resource id */
    "Button12",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCMD_1100000B_PLUS,    /* resource identifier */
    &UIFG_1100000B_PLUS,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    0,     /* prompt's resource id */
    "plus",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCMD_1100001F_MINS,    /* resource identifier */
    &UIFG_1100001F_MINS,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    0,     /* prompt's resource id */
    "Button13",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCMD_1100000D_RETURN,    /* resource identifier */
    &UIFG_1100000D_RETURN,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    0,     /* prompt's resource id */
    "backamaty",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCMD_1100000C_NO_COMMAND,    /* resource identifier */
    &UIFG_1100000C_NO_COMMAND,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    0,     /* prompt's resource id */
    "clear_amaty",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    {
    RCID_11F00008_TEXT1111,    /* resource identifier */
    &UIFG_11F00008_TEXT1111,   /* presentation style control */
    NULL,   /* state table */
    NULL,   /* disabled by table */
    RCLT_11F00008_TEXT1111,     /* prompt's resource id */
    "demo_text",   /* control's name */
    0,    /* control's reparenting struct */
    0,   /* control's farpoint tab number (if any) */
    0    /* control's farpoint page number (if any) */
    },
    WI_END_FIELD_LIST;

static WILITERAL LTBL_12700001_AMATY[] = 
    {
    { 0, 0, 0 }
    };

                       /******************************/
                       /*  Command Table for Window  */
                       /******************************/
static WICOMMAND UIC_12700001_AMATY[]
    WI_BEGIN_CMD_LIST
    {RCMD_1100000F_NO_COMMAND,"",CM_OTHER,NULL,0,0,ST_PUSHBUTTON,DEFAULT_STATUS, "Button3"},
    {RCMD_1100000E_NO_COMMAND,"",CM_OTHER,NULL,0,0,ST_PUSHBUTTON,DEFAULT_STATUS, "Button4"},
    {RCMD_11000012_NO_COMMAND,"",CM_OTHER,NULL,0,0,ST_PUSHBUTTON,DEFAULT_STATUS, "Button5"},
    {RCMD_1100001E_ENTER,"ENTER",CM_OTHER,NULL,0,RCMD_E10000D_ENTER,ST_PUSHBUTTON,DEFAULT_STATUS, "Button14"},
    {RCMD_11000011_NO_COMMAND,"",CM_OTHER,NULL,0,0,ST_PUSHBUTTON,DEFAULT_STATUS, "Button6"},
    {RCMD_11000010_NO_COMMAND,"",CM_OTHER,NULL,0,0,ST_PUSHBUTTON,DEFAULT_STATUS, "Button7"},
    {RCMD_11000014_NO_COMMAND,"",CM_OTHER,NULL,0,0,ST_PUSHBUTTON,DEFAULT_STATUS, "Button8"},
    {RCMD_11000019_NO_COMMAND,"",CM_OTHER,NULL,0,0,ST_PUSHBUTTON,DEFAULT_STATUS, "Button9"},
    {RCMD_1100001A_NO_COMMAND,"",CM_OTHER,NULL,0,0,ST_PUSHBUTTON,DEFAULT_STATUS, "Button10"},
    {RCMD_1100001B_NO_COMMAND,"",CM_OTHER,NULL,0,0,ST_PUSHBUTTON,DEFAULT_STATUS, "Button11"},
    {RCMD_1100001D_NO_COMMAND,"",CM_OTHER,NULL,0,0,ST_PUSHBUTTON,DEFAULT_STATUS, "Button12"},
    {RCMD_1100000B_PLUS,"PLUS",CM_OTHER,NULL,0,RCMD_E10000F_PLUS,ST_PUSHBUTTON,DEFAULT_STATUS, "plus"},
    {RCMD_1100001F_MINS,"MINS",CM_OTHER,NULL,0,RCMD_E100010_MINS,ST_PUSHBUTTON,DEFAULT_STATUS, "Button13"},
    {RCMD_1100000D_RETURN,"RETURN",CM_OTHER,NULL,0,RCMD_E10000B_RETURN,ST_PUSHBUTTON,DEFAULT_STATUS, "backamaty"},
    {RCMD_1100000C_NO_COMMAND,"",CM_OTHER,NULL,0,0,ST_PUSHBUTTON,DEFAULT_STATUS, "clear_amaty"},
    WI_END_CMD_LIST;

                        /****************************/
                        /*  Event Table for Window  */
                        /****************************/
static WIEVENT EVT_12700001_AMATY[]
    WI_BEGIN_EVENT_LIST
    {RCMD_1100000F_NO_COMMAND,    /* resource id of the control */
        "Click",    /* event type */
        expert_amaty_pb_1_click05,    /* event handler */
        0,    /* command */
        ' ',    /* map flag */
        0,    /* OLE event flag */
        0,    /* offset of return attribute */
        0,    /* length of return attribute */
        0,    /* datatype of return attribute */
        0},    /* decimals for return value */
    {RCMD_1100000E_NO_COMMAND,    /* resource id of the control */
        "Click",    /* event type */
        expert_amaty_pb_2_click06,    /* event handler */
        0,    /* command */
        ' ',    /* map flag */
        0,    /* OLE event flag */
        0,    /* offset of return attribute */
        0,    /* length of return attribute */
        0,    /* datatype of return attribute */
        0},    /* decimals for return value */
    {RCMD_11000012_NO_COMMAND,    /* resource id of the control */
        "Click",    /* event type */
        expert_amaty_pb_3_click07,    /* event handler */
        0,    /* command */
        ' ',    /* map flag */
        0,    /* OLE event flag */
        0,    /* offset of return attribute */
        0,    /* length of return attribute */
        0,    /* datatype of return attribute */
        0},    /* decimals for return value */
    {RCID_F700016_DROP_LIST1,    /* resource id of the control */
        "Changed",    /* event type */
        expert_amaty_dl_drop_list1_ch17,    /* event handler */
        0,    /* command */
        'Y',    /* map flag */
        0,    /* OLE event flag */
        0,    /* offset of return attribute */
        0,    /* length of return attribute */
        0,    /* datatype of return attribute */
        0},    /* decimals for return value */
    {RCMD_1100001E_ENTER,    /* resource id of the control */
        "Click",    /* event type */
        expert_amaty_pb_ok_click15,    /* event handler */
        "ENTER",    /* command */
        ' ',    /* map flag */
        0,    /* OLE event flag */
        0,    /* offset of return attribute */
        0,    /* length of return attribute */
        0,    /* datatype of return attribute */
        0},    /* decimals for return value */
    {RCMD_11000011_NO_COMMAND,    /* resource id of the control */
        "Click",    /* event type */
        expert_amaty_pb_4_click08,    /* event handler */
        0,    /* command */
        ' ',    /* map flag */
        0,    /* OLE event flag */
        0,    /* offset of return attribute */
        0,    /* length of return attribute */
        0,    /* datatype of return attribute */
        0},    /* decimals for return value */
    {RCMD_11000010_NO_COMMAND,    /* resource id of the control */
        "Click",    /* event type */
        expert_amaty_pb_5_click09,    /* event handler */
        0,    /* command */
        ' ',    /* map flag */
        0,    /* OLE event flag */
        0,    /* offset of return attribute */
        0,    /* length of return attribute */
        0,    /* datatype of return attribute */
        0},    /* decimals for return value */
    {RCMD_11000014_NO_COMMAND,    /* resource id of the control */
        "Click",    /* event type */
        expert_amaty_pb_6_click10,    /* event handler */
        0,    /* command */
        ' ',    /* map flag */
        0,    /* OLE event flag */
        0,    /* offset of return attribute */
        0,    /* length of return attribute */
        0,    /* datatype of return attribute */
        0},    /* decimals for return value */
    {RCMD_11000019_NO_COMMAND,    /* resource id of the control */
        "Click",    /* event type */
        expert_amaty_pb_7_click11,    /* event handler */
        0,    /* command */
        ' ',    /* map flag */
        0,    /* OLE event flag */
        0,    /* offset of return attribute */
        0,    /* length of return attribute */
        0,    /* datatype of return attribute */
        0},    /* decimals for return value */
    {RCMD_1100001A_NO_COMMAND,    /* resource id of the control */
        "Click",    /* event type */
        expert_amaty_pb_8_click12,    /* event handler */
        0,    /* command */
        ' ',    /* map flag */
        0,    /* OLE event flag */
        0,    /* offset of return attribute */
        0,    /* length of return attribute */
        0,    /* datatype of return attribute */
        0},    /* decimals for return value */
    {RCMD_1100001B_NO_COMMAND,    /* resource id of the control */
        "Click",    /* event type */
        expert_amaty_pb_9_click13,    /* event handler */
        0,    /* command */
        ' ',    /* map flag */
        0,    /* OLE event flag */
        0,    /* offset of return attribute */
        0,    /* length of return attribute */
        0,    /* datatype of return attribute */
        0},    /* decimals for return value */
    {RCMD_1100001D_NO_COMMAND,    /* resource id of the control */
        "Click",    /* event type */
        expert_amaty_pb_0_click14,    /* event handler */
        0,    /* command */
        ' ',    /* map flag */
        0,    /* OLE event flag */
        0,    /* offset of return attribute */
        0,    /* length of return attribute */
        0,    /* datatype of return attribute */
        0},    /* decimals for return value */
    {RCMD_1100000B_PLUS,    /* resource id of the control */
        "Click",    /* event type */
        expert_amaty_pb_plus_click01,    /* event handler */
        "PLUS",    /* command */
        ' ',    /* map flag */
        0,    /* OLE event flag */
        0,    /* offset of return attribute */
        0,    /* length of return attribute */
        0,    /* datatype of return attribute */
        0},    /* decimals for return value */
    {RCMD_1100001F_MINS,    /* resource id of the control */
        "Click",    /* event type */
        expert_amaty_pb_mine_click02,    /* event handler */
        "MINS",    /* command */
        ' ',    /* map flag */
        0,    /* OLE event flag */
        0,    /* offset of return attribute */
        0,    /* length of return attribute */
        0,    /* datatype of return attribute */
        0},    /* decimals for return value */
    {RCMD_1100000D_RETURN,    /* resource id of the control */
        "Click",    /* event type */
        expert_amaty_pb_back_click04,    /* event handler */
        0,    /* command */
        ' ',    /* map flag */
        0,    /* OLE event flag */
        0,    /* offset of return attribute */
        0,    /* length of return attribute */
        0,    /* datatype of return attribute */
        0},    /* decimals for return value */
    {RCMD_1100000C_NO_COMMAND,    /* resource id of the control */
        "Click",    /* event type */
        expert_amaty_pb_clear_click03,    /* event handler */
        0,    /* command */
        ' ',    /* map flag */
        0,    /* OLE event flag */
        0,    /* offset of return attribute */
        0,    /* length of return attribute */
        0,    /* datatype of return attribute */
        0},    /* decimals for return value */
    WI_END_EVENT_LIST;

                      /********************************/
                      /*  Menu Merge Info for Window  */
                      /********************************/
static MENUMERGE MM_12700001_AMATY[] =
    {0,0,0};

#include <citrantb.h>

static CIViewDefVal IUIMP_3C00001_CALCULAT_WIN[] = {
/* (un-)initialize import/export views. */
{DT_END, 0, 0, 0, 0, 0}};

static CIViewDefVal IUEXP_3C00001_CALCULAT_WIN[] = {
/* (un-)initialize import/export views. */
{DT_END, 0, 0, 0, 0, 0}};

static CIViewDefVal IUIMP_3C00000_AMATY[] = {
/* (un-)initialize import/export views. */
{DT_END, 0, 0, 0, 0, 0}};

static CIViewDefVal IUEXP_3C00000_AMATY[] = {
/* (un-)initialize import/export views. */
{DT_END, 0, 0, 0, 0, 0}};

                         /***************************/
                         /*  Procedure Step Tables  */
                         /***************************/

static PSTEP_TBL pstep_tbl [] =
{
    {
    PID_3C00001_CALCULAT_WIN,    /* pstep id */
    "CALCULAT_WIN",    /* pstep name */
    &glob_data,
    NULL,    /* address of import view */
    (long) sizeof(a_0105906284_ia),    /* size of import view */
    NULL,    /* address of export view */
    (long) sizeof(a_0106954861_oa),    /* size of export view */
    &HOME,    /* action block function logic */
    AF_3C00001_CALCULAT_WIN,    /* autoflow */
    ES_3C00001_CALCULAT_WIN,    /* exitstate usage */
    DF_3C00001_CALCULAT_WIN,    /* dialog flow */
    &INOUT_3C00001_CALCULAT_WIN,    /* input to output windowmap function */
    &OUTIN_3C00001_CALCULAT_WIN,    /* output to input windowmap function */
    &XRECV_3C00001_CALCULAT_WIN,    /* recv x-loadmod common format flow */
    &XRTRN_3C00001_CALCULAT_WIN,    /* rtrn x-loadmod common format flow */
    "CALCULAT",     /* initial window code */
    PS_INTERNAL,
    &IUIMP_3C00001_CALCULAT_WIN,    /* (un-)initialize import view */
    &IUEXP_3C00001_CALCULAT_WIN},    /* (un-)initialize export view */
    {
    PID_3C00000_AMATY,    /* pstep id */
    "AMATY",    /* pstep name */
    &glob_data,
    NULL,    /* address of import view */
    (long) sizeof(a_0105906281_ia),    /* size of import view */
    NULL,    /* address of export view */
    (long) sizeof(a_0106954858_oa),    /* size of export view */
    &EXPERT,    /* action block function logic */
    NULL,    /* autoflow */
    NULL,    /* exitstate usage */
    NULL,    /* dialog flow */
    &INOUT_3C00000_AMATY,    /* input to output windowmap function */
    &OUTIN_3C00000_AMATY,    /* output to input windowmap function */
    &XRECV_3C00000_AMATY,    /* recv x-loadmod common format flow */
    &XRTRN_3C00000_AMATY,    /* rtrn x-loadmod common format flow */
    "AMATY",     /* initial window code */
    PS_INTERNAL,
    &IUIMP_3C00000_AMATY,    /* (un-)initialize import view */
    &IUEXP_3C00000_AMATY},    /* (un-)initialize export view */
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
};    /* End of procedure step table */

static PSTEP_WINTBL pstep_wintbl [] =
{
    {
    PID_3C00001_CALCULAT_WIN,    /* pstep id */
    RCID_12700000_CALCULAT_WIN,    /* resource id */
    UIC_12700000_CALCULAT_WIN,    /* command Table */
    UIF_12700000_CALCULAT_WIN,    /* Field Table */
    &win_IN_12700000_CALCULAT_WIN,    /* input windowmap function */
    &win_OUT_12700000_CALCULAT_WIN,    /* output windowmap function */
    "SSD",    /* subwindow box, system placed window */
    PR_MODAL,    /* modal window */
    EVT_12700000_CALCULAT_WIN,       /* event table */
    "CALCULAT_WIN",  /* window name */
    NULL,      /* No background bitmap */
    0,         /* no bitmap rcid */
    '\0',      /* no bitmap usage */
    LTBL_12700000_CALCULAT_WIN,
    0,        /* no event parameters */
    MM_12700000_CALCULAT_WIN,       /* menu merge array */
    0    /* icon file name */
    },
    {
    PID_3C00000_AMATY,    /* pstep id */
    RCID_12700001_AMATY,    /* resource id */
    UIC_12700001_AMATY,    /* command Table */
    UIF_12700001_AMATY,    /* Field Table */
    &win_IN_12700001_AMATY,    /* input windowmap function */
    &win_OUT_12700001_AMATY,    /* output windowmap function */
    "SDD",    /* subwindow box, design placed window */
    PR_MODAL,    /* modal window */
    EVT_12700001_AMATY,       /* event table */
    "AMATY",  /* window name */
    NULL,      /* No background bitmap */
    0,         /* no bitmap rcid */
    '\0',      /* no bitmap usage */
    LTBL_12700001_AMATY,
    0,        /* no event parameters */
    MM_12700001_AMATY,       /* menu merge array */
    0    /* icon file name */
    },
    {0,0,0,0,0,0,0}
};    /* End of procedure step win table */

/* filenames of all dlls for diagrams, dialog boxes */
static WIRES wiextern_restable[]=
    {
    {"CAL"},    /* NOTE:all resources in single .dll */
    {0}    /* termination of list */
    };
/* help resources */
static  WIHELP wiextern_help_res =
    {
    RCTL_HELP,    /* string id of file name list */
    RCID_13300000_CAL,    /* resource id of help table */
    HP_HELP_KEYS,     /* resource id of keys help */
    1 /*HTML help */
    };    /* end of help resource table */

/* dde application data */
static WIDOMAIN DDED_DB00088_RESULT =
    {
    9,
    BT_LONG,
    8,
    0,
    "",
    NULL,
    FALSE,FALSE,
    NULL
    };

static IEFDDE_ATTR DDEA_A60006A_EXPORT_RESULT[] =
    {
    /* attr_name size import_item export_item domain */
    {"RESULT",sizeof(long),
     offsetof(a_0105906284_ia, result_001),
     offsetof(a_0106954861_oa, result_008),
     &UID_11F00007_RESULT},
    {0,0,0,0,0}
    }; 
static WIDOMAIN DDED_DB0007D_NUMBER2 =
    {
    6,
    BT_LONG,
    5,
    0,
    "",
    NULL,
    FALSE,FALSE,
    NULL
    };

static IEFDDE_ATTR DDEA_A60006B_EXPORT_N2ND[] =
    {
    /* attr_name size import_item export_item domain */
    {"NUMBER2",sizeof(long),
     offsetof(a_0105906284_ia, number2_002),
     offsetof(a_0106954861_oa, number2_009),
     &UID_11F00003_NUMBER2},
    {0,0,0,0,0}
    }; 
static WIDOMAIN DDED_DB0008C_NUMBER1ST =
    {
    9,
    BT_LONG,
    8,
    0,
    "",
    NULL,
    FALSE,FALSE,
    NULL
    };

static IEFDDE_ATTR DDEA_A60006C_EXPORT_N1[] =
    {
    /* attr_name size import_item export_item domain */
    {"NUMBER1ST",sizeof(long),
     offsetof(a_0105906284_ia, number1st_003),
     offsetof(a_0106954861_oa, number1st_010),
     &UID_11F00005_NUMBER1ST},
    {0,0,0,0,0}
    }; 
static WIDOMAIN DDED_DB00077_DROP_LIST1 =
    {
    2,
    BT_STRING,
    1,
    0,
    "",
    PVAL_360009F_DROP_LIST1,
    TRUE,FALSE,
    "E"
    };

static IEFDDE_ATTR DDEA_A600076_EXPORT_AMATY[] =
    {
    /* attr_name size import_item export_item domain */
    {"DROP_LIST1",sizeof(char)*2,
     offsetof(a_0105906281_ia, drop_list1_004),
     offsetof(a_0106954858_oa, drop_list1_011),
     &DDED_DB00077_DROP_LIST1},
    {0,0,0,0,0}
    }; 
static WIDOMAIN DDED_DB00078_TEXT1111 =
    {
    101,
    BT_STRING,
    100,
    0,
    "",
    NULL,
    FALSE,FALSE,
    NULL
    };

static IEFDDE_ATTR DDEA_A60006D_OUT_DEMO_TEXT[] =
    {
    /* attr_name size import_item export_item domain */
    {"TEXT1111",sizeof(char)*101,
     offsetof(a_0105906281_ia, text1111_005),
     offsetof(a_0106954858_oa, text1111_012),
     &UID_11F00008_TEXT1111},
    {0,0,0,0,0}
    }; 
static WIDOMAIN DDED_DB00093_RESULT =
    {
    9,
    BT_LONG,
    8,
    0,
    "",
    NULL,
    FALSE,FALSE,
    NULL
    };

static IEFDDE_ATTR DDEA_A60007A_OUT_RESULT[] =
    {
    /* attr_name size import_item export_item domain */
    {"RESULT",sizeof(long),
     offsetof(a_0105906281_ia, result_006),
     offsetof(a_0106954858_oa, result_013),
     &UID_11F00017_RESULT},
    {0,0,0,0,0}
    }; 
static WIDOMAIN DDED_DB00080_TOTAL_REAL =
    {
    19,
    BT_DOUBLE,
    17,
    0,
    "",
    NULL,
    FALSE,FALSE,
    NULL
    };

static IEFDDE_ATTR DDEA_A600078_OUT_N1[] =
    {
    /* attr_name size import_item export_item domain */
    {"TOTAL_REAL",sizeof(double),
     offsetof(a_0105906281_ia, total_real_007),
     offsetof(a_0106954858_oa, total_real_014),
     &UID_11F00015_TOTAL_REAL},
    {0,0,0,0,0}
    }; 
static WIDOMAIN DDED_DB00083_ALLLLLLL =
    {
    201,
    BT_STRING,
    200,
    0,
    "",
    NULL,
    FALSE,FALSE,
    NULL
    };

static IEFDDE_ATTR DDEA_A600073_OUT_TITLE_ALL[] =
    {
    /* attr_name size import_item export_item domain */
    {"ALLLLLLL",sizeof(char)*201,
     0,
     offsetof(a_0106954858_oa, alllllll_015),
     &UID_11F00013_ALLLLLLL},
    {0,0,0,0,0}
    }; 
static IEFDDE_ENTITY DDE_3C00001_CALCULAT_WIN[] =
    {
    /* view.entity_name. dim_1 dim_2 dim_3  IEFDDE_ATTR list */
    {"EXPORT_RESULT.IEF_SUPPLIED.",0,0,0,DDEA_A60006A_EXPORT_RESULT},
    {"EXPORT_N2ND.IEF_SUPPLIED.",0,0,0,DDEA_A60006B_EXPORT_N2ND},
    {"EXPORT_N1.IEF_SUPPLIED.",0,0,0,DDEA_A60006C_EXPORT_N1},
    {0,0,0,0,0}
    }; 
static IEFDDE_ENTITY DDE_3C00000_AMATY[] =
    {
    /* view.entity_name. dim_1 dim_2 dim_3  IEFDDE_ATTR list */
    {"EXPORT_AMATY.AMATY.",0,0,0,DDEA_A600076_EXPORT_AMATY},
    {"OUT_DEMO_TEXT.DEMO_TEXT_1111.",0,0,0,DDEA_A60006D_OUT_DEMO_TEXT},
    {"OUT_RESULT.IEF_SUPPLIED.",0,0,0,DDEA_A60007A_OUT_RESULT},
    {"OUT_N1.IEF_SUPPLIED.",0,0,0,DDEA_A600078_OUT_N1},
    {"OUT_TITLE_ALL.CALCULAT_NAME.",0,0,0,DDEA_A600073_OUT_TITLE_ALL},
    {0,0,0,0,0}
    }; 
static IEFDDE_GROUP DDEG_3C00001_CALCULAT_WIN[] =
    {
    /* grpvw_name i1stEntvw iFinEntvw nDims curCard*/
    {"*", 0, 3, 0, 0},
    {0, 0, 0, 0, 0}
    }; 
static IEFDDE_GROUP DDEG_3C00000_AMATY[] =
    {
    /* grpvw_name i1stEntvw iFinEntvw nDims curCard*/
    {"*", 0, 5, 0, 0},
    {0, 0, 0, 0, 0}
    }; 
static IEFDDE_TOPIC widde_topics[] =
    {
    /* window_title IEFDDE_ENTITY_list IEFDDE_GROUP_list PSTEPID */
    {"CALCULAT_WIN", DDE_3C00001_CALCULAT_WIN, DDEG_3C00001_CALCULAT_WIN, PID_3C00001_CALCULAT_WIN}, /* proc step */
    {"ASER CALCULAT", DDE_3C00001_CALCULAT_WIN, DDEG_3C00001_CALCULAT_WIN, PID_3C00001_CALCULAT_WIN}, /* window */
    {"AMATY", DDE_3C00000_AMATY, DDEG_3C00000_AMATY, PID_3C00000_AMATY}, /* proc step */
    {0, 0, 0}
    };    /* end of dde topics def */
static IEFDDE_APPLICATION widde_application =
    {
    "CAL",    /* load module name */
     widde_topics
    };    /* end of dde application index base def */

/* exit state name table */
static EXITSTATENAMETABLE exitStateNameTable[] =
{
   { 238026767, "SUBJECT_LIST" },
   { 238026766, "FLOW_TO_MENU" },
   { 238026765, "RETURN" },
   { 238026764, "ACTION_BAR_IS_INVALID" },
   { 238026763, "INVALID_COMMAND" },
   { 238026762, "VALID_DELETE" },
   { 238026761, "VALID_UPDATE" },
   { 238026760, "VALID_CREATE" },
   { 238026759, "DELETE_OK" },
   { 238026758, "UPDATE_OK" },
   { 238026757, "CREATE_OK" },
   { 238026756, "DISPLAY_OK" },
   { 238026755, "KEY_FIELD_IS_BLANK" },
   { 238026754, "KEY_CHANGE_NOT_ALLOWED" },
   { 238026753, "PROCESSING_OK" },
   { 238026752, "PROCESSING_STARTED" },
   { 238026769, "RETURN_BACK_TO_EXPERT_AMATY" },
   { 238026768, "RETURN_BACK_TO_MAIN" },
   { 0L, "" }
};


/* Extension Table */

static void *extensionTable[] = {
    (void*) "CALCULAT",
    (void*) "NONE",
    (void*) "<NONE>",
    (void*) ".",
    (void*) ",",
    (void*) "DEFAULT",
    (void*) "8600333",
    (void*) "wr",
    (void*) "1252",
    (void*) NULL, 
    (void*) &exitStateNameTable,
    (void*) NULL, 
    (void*) ET_LASTENTRY
    };

WINHEAD win_head =
    {
    pstep_tbl,
    pstep_wintbl,
    wiextern_restable,
    &wiextern_help_res,
    (char *)&glob_data,
    &widde_application,
    NULL,
    NULL,
    extensionTable,
    NULL,
    };    /* end of appl head def */

void win_IN_12700000_CALCULAT_WIN(void *dp,
a_0105906284_ia *ia,
a_0106954861_oa *oa)
{
/* Copy all window views from the window */
/* to the import view.  If the current */
/* predicate view is in a repeating group */
/* view and is a list box field, copy it */
/* to the group view backing structure to */
/* update the window list.  Copy all */
/* procedure step export views to the  */
/* import views. */
short gv1_hole = 0;
short temp = 0;
short selndx = 0;
char **vpa = WinGetVpa( dp );
ia->number1st_003 =  *(long *)(vpa[0]);
ia->number2_002 =  *(long *)(vpa[3]);
ia->result_001 =  *(long *)(vpa[5]);
return;
}

void win_OUT_12700000_CALCULAT_WIN(void *dp,
a_0106954861_oa *oa)
{
/* copy w-oa fields to window fields */
short gv1_hole = 0;
short temp = 0;
char **vpa = WinGetVpa( dp );
 *(long *)(vpa[0]) = oa->number1st_010;
memcpy(vpa[0]-6, oa->number1st_010at, sizeof(oa->number1st_010at));
 if (oa->number1st_010at[1] >= 'i')
oa->number1st_010at[1] = oa->number1st_010at[1] - 8;
 *(long *)(vpa[3]) = oa->number2_009;
memcpy(vpa[3]-6, oa->number2_009at, sizeof(oa->number2_009at));
 if (oa->number2_009at[1] >= 'i')
oa->number2_009at[1] = oa->number2_009at[1] - 8;
 *(long *)(vpa[5]) = oa->result_008;
memcpy(vpa[5]-6, oa->result_008at, sizeof(oa->result_008at));
 if (oa->result_008at[1] >= 'i')
oa->result_008at[1] = oa->result_008at[1] - 8;
return;
}

void INOUT_3C00001_CALCULAT_WIN(a_0105906284_ia *ia,
a_0106954861_oa *oa)
{
/* copy mapped fields from w-ia to w-oa for display 1st */
/* dialog flows either display 1st flows on or display 1st */
/* returns on */
short gv1_hole = 0;
oa->result_008 = ia->result_001;
oa->number1st_010 = ia->number1st_003;
oa->number2_009 = ia->number2_002;
return;
}

void OUTIN_3C00001_CALCULAT_WIN(a_0105906284_ia *ia,
a_0106954861_oa *oa)
{
/* copy mapped fields from w-oa to w-ia.  Called by */
/* win_in & dlg_in functions to populate import view */
/* before accepting window's fields */
short gv1_hole = 0;
ia->result_001 = oa->result_008;
ia->number1st_003 = oa->number1st_010;
ia->number2_002 = oa->number2_009;
return;
}

void FSEND_E400002_DLGFLOW(a_0105906281_ia *ia,
a_0106954861_oa *oa)
{
short gv1_hole = 0;
short adim1 = 0;
static TIRLOB_RETCODE lob_rc;
/* copy dialog flow mapped w-oa fields to w-ia */
ia->result_006 = oa->result_008;
}

void FRTRN_E400002_DLGFLOW(a_0106954861_oa *prev_oa,
a_0105906284_ia *ia,
a_0106954858_oa *rtrn_oa)
{
short gv1_hole = 0;
short adim1 = 0;
static TIRLOB_RETCODE lob_rc;
/* if field not in returns on view matching */
/* copy prev export view item to import view */
/* based on mapping assoc to flows on pstep */
/* */

OUTIN_3C00001_CALCULAT_WIN(ia,
    prev_oa);

/* if field in returns on view matching */
/* copy returned export view item to import view */
ia->result_001 = rtrn_oa->result_013;
}

void win_IN_12700001_AMATY(void *dp,
a_0105906281_ia *ia,
a_0106954858_oa *oa)
{
/* Copy all window views from the window */
/* to the import view.  If the current */
/* predicate view is in a repeating group */
/* view and is a list box field, copy it */
/* to the group view backing structure to */
/* update the window list.  Copy all */
/* procedure step export views to the  */
/* import views. */
short gv1_hole = 0;
short temp = 0;
short selndx = 0;
char **vpa = WinGetVpa( dp );
ia->result_006 =  *(long *)(vpa[1]);
ia->total_real_007 =  *(double *)(vpa[2]);
button_in(dp,
    6,
    &WIED_F700016_DROP_LIST1,
    ia->drop_list1_004,
    sizeof(ia->drop_list1_004) - 1);

memcpy(ia->text1111_005, vpa[19], sizeof(ia->text1111_005) - 1);
return;
}

void win_OUT_12700001_AMATY(void *dp,
a_0106954858_oa *oa)
{
/* copy w-oa fields to window fields */
short gv1_hole = 0;
short temp = 0;
char **vpa = WinGetVpa( dp );
memcpy(vpa[0], oa->alllllll_015, sizeof(oa->alllllll_015) - 1);
memcpy(vpa[0]-6, oa->alllllll_015at, sizeof(oa->alllllll_015at));
 if (oa->alllllll_015at[1] >= 'i')
oa->alllllll_015at[1] = oa->alllllll_015at[1] - 8;
 *(long *)(vpa[1]) = oa->result_013;
memcpy(vpa[1]-6, oa->result_013at, sizeof(oa->result_013at));
 if (oa->result_013at[1] >= 'i')
oa->result_013at[1] = oa->result_013at[1] - 8;
 *(double *)(vpa[2]) = oa->total_real_014;
memcpy(vpa[2]-6, oa->total_real_014at, sizeof(oa->total_real_014at));
 if (oa->total_real_014at[1] >= 'i')
oa->total_real_014at[1] = oa->total_real_014at[1] - 8;
button_out(dp,
    6,
    &WIED_F700016_DROP_LIST1,
    oa->drop_list1_011,
    sizeof(oa->drop_list1_011) - 1);

memcpy(vpa[6]-6, oa->drop_list1_011at, sizeof(oa->drop_list1_011at));
 if (oa->drop_list1_011at[1] >= 'i')
oa->drop_list1_011at[1] = oa->drop_list1_011at[1] - 8;
memcpy(vpa[19], oa->text1111_012, sizeof(oa->text1111_012) - 1);
memcpy(vpa[19]-6, oa->text1111_012at, sizeof(oa->text1111_012at));
 if (oa->text1111_012at[1] >= 'i')
oa->text1111_012at[1] = oa->text1111_012at[1] - 8;
return;
}

void INOUT_3C00000_AMATY(a_0105906281_ia *ia,
a_0106954858_oa *oa)
{
/* copy mapped fields from w-ia to w-oa for display 1st */
/* dialog flows either display 1st flows on or display 1st */
/* returns on */
short gv1_hole = 0;
Tistrcpy(oa->drop_list1_011, ia->drop_list1_004, sizeof(oa->drop_list1_011));
Tistrcpy(oa->text1111_012, ia->text1111_005, sizeof(oa->text1111_012));
oa->result_013 = ia->result_006;
oa->total_real_014 = ia->total_real_007;
return;
}

void OUTIN_3C00000_AMATY(a_0105906281_ia *ia,
a_0106954858_oa *oa)
{
/* copy mapped fields from w-oa to w-ia.  Called by */
/* win_in & dlg_in functions to populate import view */
/* before accepting window's fields */
short gv1_hole = 0;
Tistrcpy(ia->drop_list1_004, oa->drop_list1_011, sizeof(ia->drop_list1_004));
Tistrcpy(ia->text1111_005, oa->text1111_012, sizeof(ia->text1111_005));
ia->result_006 = oa->result_013;
ia->total_real_007 = oa->total_real_014;
return;
}

void XRECV_3C00001_CALCULAT_WIN(a_0105906284_ia *ia,char *envhndl)
{
/* ******************************* */
/* x-loadmod flow receive function */
/* ******************************* */
short adim1 = 0;
short adim2 = 0;
short adim3 = 0;
char yes = 'Y';
/* predicate view item */
getReceiveBuffer(envhndl,
    &ia->result_001,
    1,
    0,
    DTC_LONG,
    sizeof(long),
    0);
/* predicate view item */
getReceiveBuffer(envhndl,
    &ia->number2_002,
    1,
    0,
    DTC_LONG,
    sizeof(long),
    0);
/* predicate view item */
getReceiveBuffer(envhndl,
    &ia->number1st_003,
    1,
    0,
    DTC_LONG,
    sizeof(long),
    0);
}

void XRTRN_3C00001_CALCULAT_WIN(a_0106954861_oa *oa,char *envhndl)
{
/* ******************************* */
/* x-loadmod flow return function  */
/* ******************************* */
short adim1 = 0;
short adim2 = 0;
short adim3 = 0;
char yes = 'Y';
/* predicate view item */
putSendBuffer(envhndl,
    &oa->result_008,
    1,
    0,
    DTC_LONG,
    sizeof(long),
    0);
/* predicate view item */
putSendBuffer(envhndl,
    &oa->number2_009,
    1,
    0,
    DTC_LONG,
    sizeof(long),
    0);
/* predicate view item */
putSendBuffer(envhndl,
    &oa->number1st_010,
    1,
    0,
    DTC_LONG,
    sizeof(long),
    0);
}

void XRECV_3C00000_AMATY(a_0105906281_ia *ia,char *envhndl)
{
/* ******************************* */
/* x-loadmod flow receive function */
/* ******************************* */
short adim1 = 0;
short adim2 = 0;
short adim3 = 0;
char yes = 'Y';
/* predicate view item */
getReceiveBuffer(envhndl,
    &ia->drop_list1_004,
    1,
    0,
    DTC_STRING,
    2,
    0);
/* predicate view item */
getReceiveBuffer(envhndl,
    &ia->text1111_005,
    1,
    0,
    DTC_STRING,
    101,
    0);
/* predicate view item */
getReceiveBuffer(envhndl,
    &ia->result_006,
    1,
    0,
    DTC_LONG,
    sizeof(long),
    0);
/* predicate view item */
getReceiveBuffer(envhndl,
    &ia->total_real_007,
    1,
    0,
    DTC_DECIMAL,
    17,
    0);
}

void XRTRN_3C00000_AMATY(a_0106954858_oa *oa,char *envhndl)
{
/* ******************************* */
/* x-loadmod flow return function  */
/* ******************************* */
short adim1 = 0;
short adim2 = 0;
short adim3 = 0;
char yes = 'Y';
/* predicate view item */
putSendBuffer(envhndl,
    &oa->drop_list1_011,
    1,
    0,
    DTC_STRING,
    2,
    0);
/* predicate view item */
putSendBuffer(envhndl,
    &oa->text1111_012,
    1,
    0,
    DTC_STRING,
    101,
    0);
/* predicate view item */
putSendBuffer(envhndl,
    &oa->result_013,
    1,
    0,
    DTC_LONG,
    sizeof(long),
    0);
/* predicate view item */
putSendBuffer(envhndl,
    &oa->total_real_014,
    1,
    0,
    DTC_DECIMAL,
    17,
    0);
/* predicate view item */
putSendBuffer(envhndl,
    &oa->alllllll_015,
    1,
    0,
    DTC_STRING,
    201,
    0);
}
/* Generate AsyncCheckIgnore Stub */
void CHECK_OR_IGNORE_ASYNC_RESPONSE(rt1,
rt2,
globdata,
arview,
asyargs)
char *rt1;
char *rt2;
char *globdata;
char *arview;
char *asyargs;
{
PROC_STEP_USAGE psu_CHECKIGNORE;
ASYNC_ARGS * args;
args = (ASYNC_ARGS*) asyargs;
strcpy(psu_CHECKIGNORE.name, "CAL");
psu_CHECKIGNORE.resource_id = NULL;
psu_CHECKIGNORE.rt1 = rt1;
psu_CHECKIGNORE.rt2 = rt2;
psu_CHECKIGNORE.globdata = globdata;
strcpy(psu_CHECKIGNORE.eventType, args->eventType);
psu_CHECKIGNORE.scope = args->scope;
psu_CHECKIGNORE.statement = args->statement;
psu_CHECKIGNORE.whenset = args->whenset;
psu_CHECKIGNORE.arv = arview;
psu_CHECKIGNORE.ia = NULL;
psu_CHECKIGNORE.oa = NULL;
psu_CHECKIGNORE.ia_to_cf = NULL;
psu_CHECKIGNORE.cf_to_oa = NULL;
PsuAsync(&psu_CHECKIGNORE);
return;
}
 /**************************************************************************/
 /*                                  E O F                                 */
 /**************************************************************************/
