                                                              
/****************************************************************
 *
 *                    Source Code Generated by
 *                           CA Gen 8.6
 *
 *    Copyright (c) 2017 CA Technologies. All rights reserved.
 *
 *    Name: CALCULAT_WIN                     Date: 2017/04/09
 *    Target OS:   WINDOWS                   Time: 21:24:08
 *    Target DBMS: <NONE>                    User: mansour
 *    Access Method: Embedded SQL   
 *
 *    Generation options:
 *    Debug trace option selected
 *    Data modeling constraint enforcement not selected
 *    Optimized import view initialization not selected
 *    High performance view passing ignored for pstep
 *    Last_statement_num execution selected
 *    Enforce default values with DBMS not selected
 *    Init unspecified optional fields to NULL not selected
 *
 ***************************************************************/
/****************************************************************
 Data declarations
 ***************************************************************/
static char ief_cgen_rlse[] = "CA Gen 8.6";
static char * ss_copyright = "Copyright (c) 2017 CA Technologies. All rights reserved.";
static char ief_cgen_date[] = "2017/04/09";
static char ief_cgen_time[] = "21:24:08";
static char ief_cgen_ency[] = "9.2.A6";
static char ief_cgen_userid[] = "mansour";
static char ief_cgen_model[] = "CALCULAT";
static char ief_cgen_subset[] = "ALL";
static char ief_cgen_name[] = "CALCULAT_WIN";
#define TGT_INTERNAL
#define TGT_ANSI
#define TGT_WIN
#define TGT_WIN32
#define TGT_NODASG

#include <tiabinc.h>

/* * * * * * * * * * * * * * * * * * * * */
/* START OF IMPORT VIEWS */
/* * * * * * * * * * * * * * * * * * * * */
/* Data View Group: W_IA */
/*       DVG id name: A_0105906284_IA */
struct a_0105906284_ia
{
/* Entity View: IMPORT_RESULT */
/*        Type: IEF_SUPPLIED */
char result_001as;
long result_001;
/* Entity View: IMPORT_N2ND */
/*        Type: IEF_SUPPLIED */
char number2_002as;
long number2_002;
/* Entity View: IMPORT_N1 */
/*        Type: IEF_SUPPLIED */
char number1st_003as;
long number1st_003;
};

static struct a_0105906284_ia  *w_ia;

/* * * * * * * * * * * * * * * * * * * * */
/* START OF EXPORT VIEWS */
/* * * * * * * * * * * * * * * * * * * * */
/* Data View Group: W_OA */
/*       DVG id name: A_0106954861_OA */
struct a_0106954861_oa
{
/* Entity View: EXPORT_RESULT */
/*        Type: IEF_SUPPLIED */
char result_004as;
char result_004at[6];
long result_004;
/* Entity View: EXPORT_N2ND */
/*        Type: IEF_SUPPLIED */
char number2_005as;
char number2_005at[6];
long number2_005;
/* Entity View: EXPORT_N1 */
/*        Type: IEF_SUPPLIED */
char number1st_006as;
char number1st_006at[6];
long number1st_006;
};

static struct a_0106954861_oa  *w_oa;

/* * * * * * * * * * * * * * * * * * * * */
/* START OF EXIT STATES */
/* * * * * * * * * * * * * * * * * * * * */
static long ex_return_back_to_expert_am001 = 238026769;
static char long64bit_len[5];
/* * * * * * * * * * * * * * * * * * */
/* MISC DECLARATIONS AND PROTOTYPES  */
/*    FOLLOW AS NEEDED:              */
/* * * * * * * * * * * * * * * * * * */

static char func_0022020097_esc_flag;
static void f_22020097(void);
void home_calculat_na_pb_click01();
static char func_0417333248_esc_flag;
void home_calculat_na_pb_clear_cli02();
static char func_0417333249_esc_flag;
void home_calculat_min_pb_click03();
static char func_0417333250_esc_flag;
void home_calculat_wi_pb_multip_cl04();
static char func_0417333251_esc_flag;
void home_calculat_wi_pb_amaty_cli05();
static char func_0417333252_esc_flag;
static void f_22020097_init();
static void f_0_trace(void);
static struct
{
char Name[32];
char  *DataPtr;
long Len;
long Prec;
long Card;
short Level;
char Viewtype;
char Domain;
char  *AuxPtr;
} padview[] = {
{

"IMPORT                          ",
(char *)0L,
0L,
0L,
0L,
1,
'B',
' ',
(char *)0L,
}
,
{

"IMPORT_RESULT                   ",
(char *)0L,
0L,
0L,
0L,
2,
'V',
' ',
(char *)0L,
}
,
{

"IEF_SUPPLIED                    ",
(char *)0L,
0L,
0L,
0L,
3,
'E',
' ',
(char *)0L,
}
,
{

"RESULT                          ",
(char *)0L,
0L,
0L,
0L,
3,
'P',
'N',
(char *)0L,
}
,
{

"IMPORT_N2ND                     ",
(char *)0L,
0L,
0L,
0L,
2,
'V',
' ',
(char *)0L,
}
,
{

"IEF_SUPPLIED                    ",
(char *)0L,
0L,
0L,
0L,
3,
'E',
' ',
(char *)0L,
}
,
{

"NUMBER2                         ",
(char *)0L,
0L,
0L,
0L,
3,
'P',
'N',
(char *)0L,
}
,
{

"IMPORT_N1                       ",
(char *)0L,
0L,
0L,
0L,
2,
'V',
' ',
(char *)0L,
}
,
{

"IEF_SUPPLIED                    ",
(char *)0L,
0L,
0L,
0L,
3,
'E',
' ',
(char *)0L,
}
,
{

"NUMBER1ST                       ",
(char *)0L,
0L,
0L,
0L,
3,
'P',
'N',
(char *)0L,
}
,
{

"EXPORT                          ",
(char *)0L,
0L,
0L,
0L,
1,
'B',
' ',
(char *)0L,
}
,
{

"EXPORT_RESULT                   ",
(char *)0L,
0L,
0L,
0L,
2,
'V',
' ',
(char *)0L,
}
,
{

"IEF_SUPPLIED                    ",
(char *)0L,
0L,
0L,
0L,
3,
'E',
' ',
(char *)0L,
}
,
{

"RESULT                          ",
(char *)0L,
0L,
0L,
0L,
3,
'P',
'N',
(char *)0L,
}
,
{

"EXPORT_N2ND                     ",
(char *)0L,
0L,
0L,
0L,
2,
'V',
' ',
(char *)0L,
}
,
{

"IEF_SUPPLIED                    ",
(char *)0L,
0L,
0L,
0L,
3,
'E',
' ',
(char *)0L,
}
,
{

"NUMBER2                         ",
(char *)0L,
0L,
0L,
0L,
3,
'P',
'N',
(char *)0L,
}
,
{

"EXPORT_N1                       ",
(char *)0L,
0L,
0L,
0L,
2,
'V',
' ',
(char *)0L,
}
,
{

"IEF_SUPPLIED                    ",
(char *)0L,
0L,
0L,
0L,
3,
'E',
' ',
(char *)0L,
}
,
{

"NUMBER1ST                       ",
(char *)0L,
0L,
0L,
0L,
3,
'P',
'N',
(char *)0L,
}
,
{

"******** BOTTOM OF DATA ********",
(char *)0L,
0L,
0L,
0L,
0,
'Z',
' ',
(char *)0L,
}
,
}
;

static void padview_init(void);

static short trace_ret_code;
static struct
{
long padn;
long padsubn;
char  *pads;
} padtext[] = {
{

   0L,   0L,"+->   CALCULAT_WIN                      04/09/2017  21:24"
}
,
{

   0L,   0L,"!       IMPORTS:"
}
,
{

   0L,   0L,"!         Work View import_result ief_supplied (Transient, Optional, Import only)"
}
,
{

   0L,   0L,"!           result"
}
,
{

   0L,   0L,"!         Work View import_n2nd ief_supplied (Transient, Optional, Import only)"
}
,
{

   0L,   0L,"!           number2"
}
,
{

   0L,   0L,"!         Work View import_n1 ief_supplied (Transient, Optional, Import only)"
}
,
{

   0L,   0L,"!           number1st"
}
,
{

   0L,   0L,"!       EXPORTS:"
}
,
{

   0L,   0L,"!         Work View export_result ief_supplied (Transient, Export only)"
}
,
{

   0L,   0L,"!           result"
}
,
{

   0L,   0L,"!         Work View export_n2nd ief_supplied (Transient, Export only)"
}
,
{

   0L,   0L,"!           number2"
}
,
{

   0L,   0L,"!         Work View export_n1 ief_supplied (Transient, Export only)"
}
,
{

   0L,   0L,"!           number1st"
}
,
{

   0L,   0L,"!"
}
,
{

   0L,   0L,"!     PROCEDURE STATEMENTS"
}
,
{

   0L,   0L,"!"
}
,
{

   1L,   0L,"!  MOVE import_result ief_supplied TO export_result ief_supplied"
}
,
{

   0L,   0L,"+---"
}
,
{

   0L,   0L," "
}
,
{

   0L,   0L,"+->   EVENT:  CALCULAT_NA_PB_CLICK            "
}
,
{

   2L,   0L,"!  SET export_result ief_supplied result TO export_n1 ief_supplied number1st + export_n2nd ief_supplied number2 "
}
,
{

   0L,   0L,"+---"
}
,
{

   0L,   0L," "
}
,
{

   0L,   0L,"+->   EVENT:  CALCULAT_NA_PB_CLEAR_CLICK      "
}
,
{

   3L,   0L,"!  SET export_n1 ief_supplied number1st TO 0 "
}
,
{

   4L,   0L,"!  SET export_n2nd ief_supplied number2 TO 0 "
}
,
{

   5L,   0L,"!  SET export_result ief_supplied result TO 0 "
}
,
{

   0L,   0L,"+---"
}
,
{

   0L,   0L," "
}
,
{

   0L,   0L,"+->   EVENT:  CALCULAT_MIN_PB_CLICK           "
}
,
{

   6L,   0L,"!  SET export_result ief_supplied result TO export_n1 ief_supplied number1st - export_n2nd ief_supplied number2 "
}
,
{

   0L,   0L,"+---"
}
,
{

   0L,   0L," "
}
,
{

   0L,   0L,"+->   EVENT:  CALCULAT_WI_PB_MULTIP_CLICK     "
}
,
{

   7L,   0L,"!  SET export_result ief_supplied result TO export_n1 ief_supplied number1st * export_n2nd ief_supplied number2 "
}
,
{

   0L,   0L,"+---"
}
,
{

   0L,   0L," "
}
,
{

   0L,   0L,"+->   EVENT:  CALCULAT_WI_PB_AMATY_CLICK      "
}
,
{

   8L,   0L,"!  EXIT STATE IS return_back_to_expert_amaty"
}
,
{

   0L,   0L,"+---"
}
,
{

  -1L,   0L,"************************* BOTTOM OF DATA *************************"
}
,
}
;
/*       +->   CALCULAT_WIN                      04/09/2017  21:24                                                            */
/*       !       IMPORTS:                                                                                                     */
/*       !         Work View import_result ief_supplied (Transient, Optional, Import only)                                    */
/*       !           result                                                                                                   */
/*       !         Work View import_n2nd ief_supplied (Transient, Optional, Import only)                                      */
/*       !           number2                                                                                                  */
/*       !         Work View import_n1 ief_supplied (Transient, Optional, Import only)                                        */
/*       !           number1st                                                                                                */
/*       !       EXPORTS:                                                                                                     */
/*       !         Work View export_result ief_supplied (Transient, Export only)                                              */
/*       !           result                                                                                                   */
/*       !         Work View export_n2nd ief_supplied (Transient, Export only)                                                */
/*       !           number2                                                                                                  */
/*       !         Work View export_n1 ief_supplied (Transient, Export only)                                                  */
/*       !           number1st                                                                                                */
/*       !                                                                                                                    */
/*       !     PROCEDURE STATEMENTS                                                                                           */
/*       !                                                                                                                    */
/*     1 !  MOVE import_result ief_supplied TO export_result ief_supplied                                                     */
/*       +---                                                                                                                 */
/*                                                                                                                            */
/*       +->   EVENT:  CALCULAT_NA_PB_CLICK                                                                                   */
/*     2 !  SET export_result ief_supplied result TO export_n1 ief_supplied number1st + export_n2nd ief_supplied number2      */
/*       +---                                                                                                                 */
/*                                                                                                                            */
/*       +->   EVENT:  CALCULAT_NA_PB_CLEAR_CLICK                                                                             */
/*     3 !  SET export_n1 ief_supplied number1st TO 0                                                                         */
/*     4 !  SET export_n2nd ief_supplied number2 TO 0                                                                         */
/*     5 !  SET export_result ief_supplied result TO 0                                                                        */
/*       +---                                                                                                                 */
/*                                                                                                                            */
/*       +->   EVENT:  CALCULAT_MIN_PB_CLICK                                                                                  */
/*     6 !  SET export_result ief_supplied result TO export_n1 ief_supplied number1st - export_n2nd ief_supplied number2      */
/*       +---                                                                                                                 */
/*                                                                                                                            */
/*       +->   EVENT:  CALCULAT_WI_PB_MULTIP_CLICK                                                                            */
/*     7 !  SET export_result ief_supplied result TO export_n1 ief_supplied number1st * export_n2nd ief_supplied number2      */
/*       +---                                                                                                                 */
/*                                                                                                                            */
/*       +->   EVENT:  CALCULAT_WI_PB_AMATY_CLICK                                                                             */
/*     8 !  EXIT STATE IS return_back_to_expert_amaty                                                                         */
/*       +---                                                                                                                 */



/* * * * * * * * * * * * * * * * * * * */
/* ACTION BLOCK FUNCTION DECLARATIONS  */
/* * * * * * * * * * * * * * * * * * * */

void HOME(in_runtime_parm1,
in_runtime_parm2,
in_globdata,
import_view,
export_view)
char  *in_runtime_parm1;
char  *in_runtime_parm2;
struct ief_globdata  *in_globdata;
struct a_0105906284_ia  *import_view;
struct a_0106954861_oa  *export_view;
{
ief_runtime_parm1 = in_runtime_parm1;
ief_runtime_parm2 = in_runtime_parm2;
globdata = in_globdata;
w_ia = import_view;
w_oa = export_view;

++(NestingLevel);
 if (setjmp(excp_jumpbuf))
{
}
 else {
f_22020097_init(1);
f_22020097();

}
NestingLevel--;
strcpy(last_stmt_num_saved, globdata->psmgr_debug_data.last_statement_num);
globdata->psmgr_debug_data.last_statement_num = "9999999999";
f_0_trace();
globdata->psmgr_debug_data.last_statement_num = last_stmt_num_saved;
return;
}


static void f_22020097(void)
{
func_0022020097_esc_flag = '\0';
strcpy(globdata->psmgr_debug_data.cur_ab_id, "0022020097");
strcpy(globdata->psmgr_debug_data.cur_ab_name, "CALCULAT_WIN");
padview_init();
globdata->psmgr_debug_data.last_statement_num = "0000000000";
f_0_trace();
globdata->psmgr_debug_data.last_statement_num = "0000000001";
f_0_trace();
 if (trace_ret_code != 8)
{
w_oa->result_004 = w_ia->result_001;
}
}


/* * * * * * * * * * * * * * * * * * * */
/* EVENT HANDLER FUNCTION DECLARATIONS  */
/* * * * * * * * * * * * * * * * * * * */

void home_calculat_na_pb_click01(in_runtime_parm1,
in_runtime_parm2,
in_globdata,
import_view,
export_view)
char  *in_runtime_parm1;
char  *in_runtime_parm2;
struct ief_globdata  *in_globdata;
struct a_0105906284_ia  *import_view;
struct a_0106954861_oa  *export_view;
{
ief_runtime_parm1 = in_runtime_parm1;
ief_runtime_parm2 = in_runtime_parm2;
globdata = in_globdata;
w_ia = import_view;
w_oa = export_view;

 if (setjmp(excp_jumpbuf))
{
}
 else {
f_22020097_init(0);
func_0022020097_esc_flag = '\0';
func_0417333248_esc_flag = '\0';
strcpy(globdata->psmgr_debug_data.cur_ab_id, "0022020097");
strcpy(globdata->psmgr_debug_data.cur_ab_name, "CALCULAT_NA_PB_CLICK");
strcpy(globdata->tracedata.curr_event_type, "Click");
padview_init();
globdata->psmgr_debug_data.last_statement_num = "0000000000";
f_0_trace();
globdata->psmgr_debug_data.last_statement_num = "0000000002";
f_0_trace();
 if (trace_ret_code != 8)
{
w_oa->result_004 = tird2dc1((double)
((double) w_oa->number1st_006  +  (double) w_oa->number2_005), 0, 0, 8);
}
}

strcpy(last_stmt_num_saved, globdata->psmgr_debug_data.last_statement_num);
globdata->psmgr_debug_data.last_statement_num = "9999999999";
f_0_trace();
globdata->psmgr_debug_data.last_statement_num = last_stmt_num_saved;
return;
}

void home_calculat_na_pb_clear_cli02(in_runtime_parm1,
in_runtime_parm2,
in_globdata,
import_view,
export_view)
char  *in_runtime_parm1;
char  *in_runtime_parm2;
struct ief_globdata  *in_globdata;
struct a_0105906284_ia  *import_view;
struct a_0106954861_oa  *export_view;
{
ief_runtime_parm1 = in_runtime_parm1;
ief_runtime_parm2 = in_runtime_parm2;
globdata = in_globdata;
w_ia = import_view;
w_oa = export_view;

 if (setjmp(excp_jumpbuf))
{
}
 else {
f_22020097_init(0);
func_0022020097_esc_flag = '\0';
func_0417333249_esc_flag = '\0';
strcpy(globdata->psmgr_debug_data.cur_ab_id, "0022020097");
strcpy(globdata->psmgr_debug_data.cur_ab_name,
    "CALCULAT_NA_PB_CLEAR_CLICK");
strcpy(globdata->tracedata.curr_event_type, "Click");
padview_init();
globdata->psmgr_debug_data.last_statement_num = "0000000000";
f_0_trace();
globdata->psmgr_debug_data.last_statement_num = "0000000003";
f_0_trace();
 if (trace_ret_code != 8)
{
w_oa->number1st_006 = tird2dc1((double)0, 0, 0, 8);
}
globdata->psmgr_debug_data.last_statement_num = "0000000004";
f_0_trace();
 if (trace_ret_code != 8)
{
w_oa->number2_005 = tird2dc1((double)0, 0, 0, 5);
}
globdata->psmgr_debug_data.last_statement_num = "0000000005";
f_0_trace();
 if (trace_ret_code != 8)
{
w_oa->result_004 = tird2dc1((double)0, 0, 0, 8);
}
}

strcpy(last_stmt_num_saved, globdata->psmgr_debug_data.last_statement_num);
globdata->psmgr_debug_data.last_statement_num = "9999999999";
f_0_trace();
globdata->psmgr_debug_data.last_statement_num = last_stmt_num_saved;
return;
}

void home_calculat_min_pb_click03(in_runtime_parm1,
in_runtime_parm2,
in_globdata,
import_view,
export_view)
char  *in_runtime_parm1;
char  *in_runtime_parm2;
struct ief_globdata  *in_globdata;
struct a_0105906284_ia  *import_view;
struct a_0106954861_oa  *export_view;
{
ief_runtime_parm1 = in_runtime_parm1;
ief_runtime_parm2 = in_runtime_parm2;
globdata = in_globdata;
w_ia = import_view;
w_oa = export_view;

 if (setjmp(excp_jumpbuf))
{
}
 else {
f_22020097_init(0);
func_0022020097_esc_flag = '\0';
func_0417333250_esc_flag = '\0';
strcpy(globdata->psmgr_debug_data.cur_ab_id, "0022020097");
strcpy(globdata->psmgr_debug_data.cur_ab_name, "CALCULAT_MIN_PB_CLICK");
strcpy(globdata->tracedata.curr_event_type, "Click");
padview_init();
globdata->psmgr_debug_data.last_statement_num = "0000000000";
f_0_trace();
globdata->psmgr_debug_data.last_statement_num = "0000000006";
f_0_trace();
 if (trace_ret_code != 8)
{
w_oa->result_004 = tird2dc1((double)
((double) w_oa->number1st_006  -  (double) w_oa->number2_005), 0, 0, 8);
}
}

strcpy(last_stmt_num_saved, globdata->psmgr_debug_data.last_statement_num);
globdata->psmgr_debug_data.last_statement_num = "9999999999";
f_0_trace();
globdata->psmgr_debug_data.last_statement_num = last_stmt_num_saved;
return;
}

void home_calculat_wi_pb_multip_cl04(in_runtime_parm1,
in_runtime_parm2,
in_globdata,
import_view,
export_view)
char  *in_runtime_parm1;
char  *in_runtime_parm2;
struct ief_globdata  *in_globdata;
struct a_0105906284_ia  *import_view;
struct a_0106954861_oa  *export_view;
{
ief_runtime_parm1 = in_runtime_parm1;
ief_runtime_parm2 = in_runtime_parm2;
globdata = in_globdata;
w_ia = import_view;
w_oa = export_view;

 if (setjmp(excp_jumpbuf))
{
}
 else {
f_22020097_init(0);
func_0022020097_esc_flag = '\0';
func_0417333251_esc_flag = '\0';
strcpy(globdata->psmgr_debug_data.cur_ab_id, "0022020097");
strcpy(globdata->psmgr_debug_data.cur_ab_name,
    "CALCULAT_WI_PB_MULTIP_CLICK");
strcpy(globdata->tracedata.curr_event_type, "Click");
padview_init();
globdata->psmgr_debug_data.last_statement_num = "0000000000";
f_0_trace();
globdata->psmgr_debug_data.last_statement_num = "0000000007";
f_0_trace();
 if (trace_ret_code != 8)
{
w_oa->result_004 = tird2dc1((double)
((double) w_oa->number1st_006  *  (double) w_oa->number2_005), 0, 0, 8);
}
}

strcpy(last_stmt_num_saved, globdata->psmgr_debug_data.last_statement_num);
globdata->psmgr_debug_data.last_statement_num = "9999999999";
f_0_trace();
globdata->psmgr_debug_data.last_statement_num = last_stmt_num_saved;
return;
}

void home_calculat_wi_pb_amaty_cli05(in_runtime_parm1,
in_runtime_parm2,
in_globdata,
import_view,
export_view)
char  *in_runtime_parm1;
char  *in_runtime_parm2;
struct ief_globdata  *in_globdata;
struct a_0105906284_ia  *import_view;
struct a_0106954861_oa  *export_view;
{
ief_runtime_parm1 = in_runtime_parm1;
ief_runtime_parm2 = in_runtime_parm2;
globdata = in_globdata;
w_ia = import_view;
w_oa = export_view;

 if (setjmp(excp_jumpbuf))
{
}
 else {
f_22020097_init(0);
func_0022020097_esc_flag = '\0';
func_0417333252_esc_flag = '\0';
strcpy(globdata->psmgr_debug_data.cur_ab_id, "0022020097");
strcpy(globdata->psmgr_debug_data.cur_ab_name,
    "CALCULAT_WI_PB_AMATY_CLICK");
strcpy(globdata->tracedata.curr_event_type, "Click");
padview_init();
globdata->psmgr_debug_data.last_statement_num = "0000000000";
f_0_trace();
globdata->psmgr_debug_data.last_statement_num = "0000000008";
f_0_trace();
 if (trace_ret_code != 8)
{
globdata->psmgr_exit_state = ex_return_back_to_expert_am001;
memset(globdata->psmgr_exit_infomsg, ' ', sizeof(globdata->psmgr_exit_infomsg));
globdata->psmgr_exit_infomsg[sizeof(globdata->psmgr_exit_infomsg) - 1] = '\0';
globdata->psmgr_rollback_rqsted = ' ';
globdata->psmgr_exit_msgtype = 'N';
}
}

strcpy(last_stmt_num_saved, globdata->psmgr_debug_data.last_statement_num);
globdata->psmgr_debug_data.last_statement_num = "9999999999";
f_0_trace();
globdata->psmgr_debug_data.last_statement_num = last_stmt_num_saved;
return;
}


/* * * * * * * * * * * * * * * * * * * */
/* SUBORDINATE FUNCTIONS */
/* * * * * * * * * * * * * * * * * * * */


/* * * * * * * * * * * * * * * * * * */
/* INITIALIZATION UTILITY FUNCTIONS  */
/* * * * * * * * * * * * * * * * * * */

static void f_22020097_init(doall)
int doall;
{

pda_queue_cmcb = &da_queue_cmcb;
pda_queue_cmcb->dqe.da_queue_entid = 0;

pda_queue_cmcb->dqr.da_queue_relmmid = 0;

memcpy(pda_queue_cmcb->da_queue_max,
    "0500",
    sizeof(pda_queue_cmcb->da_queue_max));

pda_queue_cmcb->pointer_flag = 'U';
 if (NestingLevel < 2)
{
}
 if (doall)
{
memset(&w_oa->result_004, '\0', sizeof(w_oa->result_004));
memset(&w_oa->number2_005, '\0', sizeof(w_oa->number2_005));
memset(&w_oa->number1st_006, '\0', sizeof(w_oa->number1st_006));
}
 if (doall)
{
}
}
static void f_0_trace(void)
{
trace_ret_code = TIRTRACE(ief_runtime_parm1,
    ief_runtime_parm2,
    globdata,
    padtext,
    padview);
 if (trace_ret_code == 20)
{
longjmp(excp_jumpbuf, TRACE_EXCEPTION);
}
return;
}
static void padview_init(void)
{
padview[0].DataPtr = (char *)(w_ia);
padview[0].Len = sizeof(*w_ia);
padview[3].DataPtr = (char *)(&w_ia->result_001);
padview[3].AuxPtr = (char *)(&w_ia->result_001as);
padview[3].Len = 8;
padview[6].DataPtr = (char *)(&w_ia->number2_002);
padview[6].AuxPtr = (char *)(&w_ia->number2_002as);
padview[6].Len = 5;
padview[9].DataPtr = (char *)(&w_ia->number1st_003);
padview[9].AuxPtr = (char *)(&w_ia->number1st_003as);
padview[9].Len = 8;
padview[10].DataPtr = (char *)(w_oa);
padview[10].Len = sizeof(*w_oa);
padview[13].DataPtr = (char *)(&w_oa->result_004);
padview[13].AuxPtr = (char *)(&w_oa->result_004as);
padview[13].Len = 8;
padview[16].DataPtr = (char *)(&w_oa->number2_005);
padview[16].AuxPtr = (char *)(&w_oa->number2_005as);
padview[16].Len = 5;
padview[19].DataPtr = (char *)(&w_oa->number1st_006);
padview[19].AuxPtr = (char *)(&w_oa->number1st_006as);
padview[19].Len = 8;
}
