package calculat.CALCULAT.Windows;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//             Servlet Manager Source Code Generated by
//                            CA Gen 8.6
//
//     Copyright (c) 2017 CA Technologies. All rights reserved.
//
//    Model Name:  CALCULAT
//
//    Load Mod:    CALCULAT                  Date: 17/04/09
//    Target OS:   JVM                       Time: 22:59:12
//    Target DBMS: JDBC                      User: mansour
//    Target GUI:  INTERNET                 
//    Dialect:     Default                  
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.reflect.*;
import java.util.*;
import java.io.*;
import java.math.*;
import com.ca.gen.smrt.*;
import com.ca.gen.smrt.controls.*;
import com.ca.gen.smrt.events.*;
import com.ca.gen.fmrt.*;
import com.ca.gen.wmrt.*;
import com.ca.gen.wmrt.controls.*;
import com.ca.gen.wmrt.controls.listboxsupport.*;
import com.ca.gen.wmrt.commands.*;
import com.ca.gen.wmrt.events.*;
import com.ca.gen.wmrt.editpatterns.*;
import com.ca.gen.abrt.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.odc.*;

public class CALCULAT_WIN extends ServletWindow implements Serializable
{
  private static final int windowResourceId = calculat.CALCULAT.LoadModule.RCID_12700000_CALCULAT_WIN;
  
  public final static int getWindowResourceId()
  {
    return(windowResourceId);
  }
  
                     /**************************************/
                     /*  Button lists and Fldgroup tables  */
                     /**************************************/
  
   public final static Domain UID_11F00005_NUMBER1ST = Domain.getInstance(
      8,
      Domain.BT_LONG,
      8,
      (short)0,
      null,
      null,
      false,
      false,    // domain= 'N' case sensitive ='N' translate ='N'
      null
      );
  
   public final static Domain UID_11F00003_NUMBER2 = Domain.getInstance(
      5,
      Domain.BT_LONG,
      5,
      (short)0,
      null,
      null,
      false,
      false,    // domain= 'N' case sensitive ='N' translate ='N'
      null
      );
  
   public final static Domain UID_11F00007_RESULT = Domain.getInstance(
      8,
      Domain.BT_LONG,
      8,
      (short)0,
      null,
      null,
      false,
      false,    // domain= 'N' case sensitive ='N' translate ='N'
      null
      );
  
  
                          /******************************/
                         /*  Command Table for Window  */
                         /******************************/
  
  private final static Command UIC_12700000_CALCULAT_WIN[] = 
      {
    new ServletCommand(calculat.CALCULAT.LoadModule.RCMD_11000000_PLUS,"PLUS",Command.CM_OTHER,
    0,
    null,
    calculat.CALCULAT.LoadModule.RCMD_E10000F_PLUS,
    State.ST_PUSHBUTTON,
     "plus",""),
    
    new ServletCommand(calculat.CALCULAT.LoadModule.RCMD_11000002_MINS,"MINS",Command.CM_OTHER,
    0,
    null,
    calculat.CALCULAT.LoadModule.RCMD_E100010_MINS,
    State.ST_PUSHBUTTON,
     "mins",""),
    
    new ServletCommand(calculat.CALCULAT.LoadModule.RCMD_11000006_NO_COMMAND,"",Command.CM_OTHER,
    0,
    null,
    0,
    State.ST_PUSHBUTTON,
     "multiply",""),
    
    new ServletCommand(calculat.CALCULAT.LoadModule.RCMD_1100000A_NO_COMMAND,"",Command.CM_OTHER,
    0,
    null,
    0,
    State.ST_PUSHBUTTON,
     "Amaty",""),
    
    new ServletCommand(calculat.CALCULAT.LoadModule.RCMD_11000009_CLEAR,"CLEAR",Command.CM_OTHER,
    0,
    null,
    calculat.CALCULAT.LoadModule.RCMD_E100004_CLEAR,
    State.ST_PUSHBUTTON,
     "Button1",""),
    
  }
  ;
  
                           /****************************/
                          /*  Event Table for Window  */
                          /****************************/
  
  private final static Event EVT_12700000_CALCULAT_WIN[] =
      {
    new Event( 
    calculat.CALCULAT.LoadModule.RCMD_11000000_PLUS, // resource id of the control
    "Click", // event type
    "home_calculat_na_pb_click01", // event handler
    null,// command
    ' ', // map flag
    false, // OLE event flag
    (short)0, // offset of return attribute
    (short)0, // length of return attribute
    ' ',// datatype of return attribute
    (short)0// decimals for return value
    ),
    
    new Event( 
    calculat.CALCULAT.LoadModule.RCMD_11000002_MINS, // resource id of the control
    "Click", // event type
    "home_calculat_min_pb_click03", // event handler
    null,// command
    ' ', // map flag
    false, // OLE event flag
    (short)0, // offset of return attribute
    (short)0, // length of return attribute
    ' ',// datatype of return attribute
    (short)0// decimals for return value
    ),
    
    new Event( 
    calculat.CALCULAT.LoadModule.RCMD_11000006_NO_COMMAND, // resource id of the control
    "Click", // event type
    "home_calculat_wi_pb_multip_cl04", // event handler
    null,// command
    ' ', // map flag
    false, // OLE event flag
    (short)0, // offset of return attribute
    (short)0, // length of return attribute
    ' ',// datatype of return attribute
    (short)0// decimals for return value
    ),
    
    new Event( 
    calculat.CALCULAT.LoadModule.RCMD_1100000A_NO_COMMAND, // resource id of the control
    "Click", // event type
    "home_calculat_wi_pb_amaty_cli05", // event handler
    null,// command
    ' ', // map flag
    false, // OLE event flag
    (short)0, // offset of return attribute
    (short)0, // length of return attribute
    ' ',// datatype of return attribute
    (short)0// decimals for return value
    ),
    
    new Event( 
    calculat.CALCULAT.LoadModule.RCMD_11000009_CLEAR, // resource id of the control
    "Click", // event type
    "home_calculat_na_pb_clear_cli02", // event handler
    null,// command
    ' ', // map flag
    false, // OLE event flag
    (short)0, // offset of return attribute
    (short)0, // length of return attribute
    ' ',// datatype of return attribute
    (short)0// decimals for return value
    ),
    
  }
  ;
  public static Event [] events = EVT_12700000_CALCULAT_WIN;    /* event table */
  
  public final static Event [] getEvents()
  {
    return(events);
  }
  
  private static int pStepId = calculat.CALCULAT.LoadModule.PID_3C00001_CALCULAT_WIN;
  private static Command [] commands = UIC_12700000_CALCULAT_WIN;
  private static char windowClass     = PR_SUBWINDOW;    /* subwindow box */
  private static char modality = PR_MODAL;    /* modal window */
  private static String windowName = "CALCULAT_WIN";  /* window name */
  private static String htmlfileName    = "CALCULAT_WIN";  /* htmlfile name */
  private static String _bitmapName = null; /* No background bitmap */
  private static char _bitmapUsage  = ' ';  /* no bitmap usage(Center/Scale/Tile) */
  private static String execUnit    = "CALCULAT";
  private static String title       = "ASER CALCULAT";
  private static int _height        = 248;
  private static int _width         = 812;
  public int getPstepId() { return pStepId; }         
  @Override public Command[] getCommands() { return commands; } 
  
  public CALCULAT_WIN()
  {
    setCssClass("DFGUIWIN CALCULAT_WIN");
        setWindowClass(windowClass);
        setModality( modality );
        setWindowName(windowName);
        setHtmlFileName(htmlfileName);
        setBitmapName(_bitmapName);
        setBitmapUsage(_bitmapUsage);
        setExecUnit(execUnit);
        setTitle(title);
        setHeight(_height);
        setWidth(_width);
    
    // Control management is internal to the Control
    new ServletSingleLineEdit(calculat.CALCULAT.LoadModule.RCID_11F00005_NUMBER1ST,
                     0,
                     this,
                     "Number1",
                     UID_11F00005_NUMBER1ST,
                     "DFGUISLE Number1",
               "DFGUIPRM Number1LblSpan");
    new ServletCommandButton(calculat.CALCULAT.LoadModule.RCMD_11000000_PLUS,
                      1,
                     this,
                      "plus","DFGUIPSB plus");
    new ServletCommandButton(calculat.CALCULAT.LoadModule.RCMD_11000002_MINS,
                      2,
                     this,
                      "mins","DFGUIPSB mins");
    new ServletSingleLineEdit(calculat.CALCULAT.LoadModule.RCID_11F00003_NUMBER2,
                     3,
                     this,
                     "Number2",
                     UID_11F00003_NUMBER2,
                     "DFGUISLE Number2",
               "DFGUIPRM Number2LblSpan");
    new ServletCommandButton(calculat.CALCULAT.LoadModule.RCMD_11000006_NO_COMMAND,
                      4,
                     this,
                      "multiply","DFGUIPSB multiply");
    new ServletSingleLineTextField(calculat.CALCULAT.LoadModule.RCID_11F00007_RESULT,
                     5,
                     this,
                     "Field1",
                     UID_11F00007_RESULT,
                     true,                 "DFGUISLE Field1",
               "DFGUIPRM Field1LblSpan");
    new ServletCommandButton(calculat.CALCULAT.LoadModule.RCMD_1100000A_NO_COMMAND,
                      6,
                     this,
                      "Amaty","DFGUIPSB Amaty");
    new ServletCommandButton(calculat.CALCULAT.LoadModule.RCMD_11000009_CLEAR,
                      7,
                     this,
                      "Button1","DFGUIPSB Button1");
    
    for (int i = 0; i < LiteralArray.length; i++) { 
         this.addObject(LiteralArray[i]); 
    } 
  }
  
  public final Object LiteralArray[] = {
  };
  
  @Override public final void in_windowmap(Window win, IImportView ia, IExportView oa)
  {
    // input windowmap function
    win_IN_12700000_CALCULAT_WIN(win,
          (calculat.HOME_IA)ia, (calculat.HOME_OA)oa);
  }
  
  @Override public final void out_windowmap(Window win, IExportView oa)
  {
    // output windowmap function
    win_OUT_12700000_CALCULAT_WIN(win,
          (calculat.HOME_OA)oa);
  }
  
  
  public void win_IN_12700000_CALCULAT_WIN(Window win, calculat.HOME_IA ia, calculat.HOME_OA oa)
  {
    // Copy all window views from the window
    // to the import view.  If the current
    // predicate view is in a repeating group
    // view and is a list box field, copy it
    // to the group view backing structure to
    // update the window list.  Copy all
    // procedure step export views to the 
    // import views. 
    
    int gv_X1 = 0;
    ia.ImportN1IefSuppliedNumber1st = IntAttr.valueOf(((Control) getControlMap().get(new Integer(0))).getVPA());
    ia.ImportN2ndIefSuppliedNumber2 = IntAttr.valueOf(((Control) getControlMap().get(new Integer(3))).getVPA());
    ia.ImportResultIefSuppliedResult = IntAttr.valueOf(((Control) getControlMap().get(new Integer(5))).getVPA());
  }
  
  public void win_OUT_12700000_CALCULAT_WIN(Window win, calculat.HOME_OA oa)
  {
    // copy w-oa fields to window fields
    
    int gv_X1 = 0;
    ((Control) getControlMap().get(new Integer(0))).setVPA(IntAttr.toString(oa.ExportN1IefSuppliedNumber1st),
      oa.ExportN1IefSuppliedNumber1st_AT);
    ((Control) getControlMap().get(new Integer(3))).setVPA(IntAttr.toString(oa.ExportN2ndIefSuppliedNumber2),
      oa.ExportN2ndIefSuppliedNumber2_AT);
    ((Control) getControlMap().get(new Integer(5))).setVPA(IntAttr.toString(oa.ExportResultIefSuppliedResult),
      oa.ExportResultIefSuppliedResult_AT);
  }
  
} // end of CALCULAT_WIN class 
