package calculat;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2017 CA Technologies. All rights reserved.
//
//    Name: EXPERT_IA                        Date: 2017/04/09
//    User: mansour                          Time: 22:59:14
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;
import com.ca.gen.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF IMPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: EXPERT_IA
 **/
public class EXPERT_IA extends ViewBase implements IImportView, Serializable
{
  static VDF localVdf = null;
  
  // Entity View: IMPORT_AMATY_LIST
  //        Type: AMATY
  /**
   * Attribute missing flag for: ImportAmatyListAmatyDropList1
   **/
  public char ImportAmatyListAmatyDropList1_AS;
  /**
   * Attribute for: ImportAmatyListAmatyDropList1
   * Domain: Text
   * Length: 1
   * Varying Length: N
   **/
  public String ImportAmatyListAmatyDropList1;
  // Entity View: IN_DEMO_TEXT
  //        Type: DEMO_TEXT_1111
  /**
   * Attribute missing flag for: InDemoTextDemoText1111Text1111
   **/
  public char InDemoTextDemoText1111Text1111_AS;
  /**
   * Attribute for: InDemoTextDemoText1111Text1111
   * Domain: Text
   * Length: 100
   * Varying Length: N
   **/
  public String InDemoTextDemoText1111Text1111;
  // Entity View: IN_RESULT
  //        Type: IEF_SUPPLIED
  /**
   * Attribute missing flag for: InResultIefSuppliedResult
   **/
  public char InResultIefSuppliedResult_AS;
  /**
   * Attribute for: InResultIefSuppliedResult
   * Domain: Number
   * Length: 8
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public int InResultIefSuppliedResult;
  // Entity View: IN_N1
  //        Type: IEF_SUPPLIED
  /**
   * Attribute missing flag for: InN1IefSuppliedTotalReal
   **/
  public char InN1IefSuppliedTotalReal_AS;
  /**
   * Attribute for: InN1IefSuppliedTotalReal
   * Domain: Number
   * Length: 17
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public double InN1IefSuppliedTotalReal;
  /**
   * Default Constructor
   **/
  
  public EXPERT_IA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public EXPERT_IA(EXPERT_IA orig)
  {
    copyFrom(orig);
  }
  /**
   * Static instance creator function
   **/
  
  public static EXPERT_IA getInstance()
  {
    return new EXPERT_IA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new EXPERT_IA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    ImportAmatyListAmatyDropList1_AS = ' ';
    ImportAmatyListAmatyDropList1 = " ";
    InDemoTextDemoText1111Text1111_AS = ' ';
    InDemoTextDemoText1111Text1111 = 
      "                                                                                                    ";
    InResultIefSuppliedResult_AS = ' ';
    InResultIefSuppliedResult = 0;
    InN1IefSuppliedTotalReal_AS = ' ';
    InN1IefSuppliedTotalReal = 0.0;
  }
  /**
   * Gets the VDF array for the instance, initialized.
   **/
  
  public static VDF getViewDefinition()
  {
    if ( localVdf == null )
    {
      VDFEntry [] vdfEntries = {
        new VDFEntry((int)1, "", "ImportAmatyListAmaty", "Amaty", "DropList1", VDFEntry.TYPE_STRING, (short)1, (short)0, 1, (short)0,
           null), 
        new VDFEntry((int)2, "", "InDemoTextDemoText1111", "DemoText1111", "Text1111", VDFEntry.TYPE_STRING, (short)1, (short)0, 100,
           (short)0, null), 
        new VDFEntry((int)3, "", "InResultIefSupplied", "IefSupplied", "Result", VDFEntry.TYPE_INT, (short)1, (short)0, 8, (short)0, 
          null), 
        new VDFEntry((int)4, "", "InN1IefSupplied", "IefSupplied", "TotalReal", VDFEntry.TYPE_DOUBLE, (short)1, (short)0, 17, (short)
          0, null), 
      };
      localVdf = new VDF(vdfEntries);
    }
    try {
      VDF result = (VDF)localVdf.clone();
      result.initViewData();
      return result;
    } catch( CloneNotSupportedException e ) {
      return null;
    }
  }
  
  /**
   * Gets the VDF version of the current state of the instance.
   **/
  public VDF getVDF()
  {
    VDF vdf = getViewDefinition();
    // predicate view item
    vdf.getEntries()[0].getDataValue().setObject(ImportAmatyListAmatyDropList1);
    // predicate view item
    vdf.getEntries()[1].getDataValue().setObject(InDemoTextDemoText1111Text1111);
    // predicate view item
    vdf.getEntries()[2].getDataValue().setObject(new Integer(InResultIefSuppliedResult));
    // predicate view item
    vdf.getEntries()[3].getDataValue().setObject(new Double(InN1IefSuppliedTotalReal));
    return(vdf);
  }
  
  /**
   * Sets the current state of the instance to the VDF version.
   **/
  public void setFromVDF(VDF vdf)
  {
    // predicate view item
    if ( vdf.getEntries()[0].getDataValue().getObject() != null )
    {
      ImportAmatyListAmatyDropList1 = ((String)vdf.getEntries()[0].getDataValue().getObject());
    }
    else 
    {
      ImportAmatyListAmatyDropList1 = " ";
    }
    // predicate view item
    if ( vdf.getEntries()[1].getDataValue().getObject() != null )
    {
      InDemoTextDemoText1111Text1111 = ((String)vdf.getEntries()[1].getDataValue().getObject());
    }
    else 
    {
      InDemoTextDemoText1111Text1111 = 
        "                                                                                                    ";
    }
    // predicate view item
    if ( vdf.getEntries()[2].getDataValue().getObject() != null )
    {
      InResultIefSuppliedResult = ((Integer)vdf.getEntries()[2].getDataValue().getObject()).intValue();
    }
    else 
    {
      InResultIefSuppliedResult = 0;
    }
    // predicate view item
    if ( vdf.getEntries()[3].getDataValue().getObject() != null )
    {
      InN1IefSuppliedTotalReal = ((Double)vdf.getEntries()[3].getDataValue().getObject()).doubleValue();
    }
    else 
    {
      InN1IefSuppliedTotalReal = 0.0;
    }
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(IImportView orig)
  {
    this.copyFrom((EXPERT_IA) orig);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(EXPERT_IA orig)
  {
    ImportAmatyListAmatyDropList1_AS = orig.ImportAmatyListAmatyDropList1_AS;
    ImportAmatyListAmatyDropList1 = orig.ImportAmatyListAmatyDropList1;
    InDemoTextDemoText1111Text1111_AS = orig.InDemoTextDemoText1111Text1111_AS;
    InDemoTextDemoText1111Text1111 = orig.InDemoTextDemoText1111Text1111;
    InResultIefSuppliedResult_AS = orig.InResultIefSuppliedResult_AS;
    InResultIefSuppliedResult = orig.InResultIefSuppliedResult;
    InN1IefSuppliedTotalReal_AS = orig.InN1IefSuppliedTotalReal_AS;
    InN1IefSuppliedTotalReal = orig.InN1IefSuppliedTotalReal;
  }
}
