package calculat;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2017 CA Technologies. All rights reserved.
//
//    Name: EXPERT_LA                        Date: 2017/04/09
//    User: mansour                          Time: 22:59:14
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;
import com.ca.gen.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF LOCAL VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: EXPERT_LA
 **/
public class EXPERT_LA extends ViewBase implements ILocalView, Serializable
{
  // Entity View: LOCAL_FLAG
  //        Type: IEF_SUPPLIED
  /**
   * Attribute missing flag for: LocalFlagIefSuppliedSelectChar
   **/
  public char LocalFlagIefSuppliedSelectChar_AS;
  /**
   * Attribute for: LocalFlagIefSuppliedSelectChar
   * Domain: Text
   * Length: 1
   * Varying Length: N
   **/
  public String LocalFlagIefSuppliedSelectChar;
  // Entity View: LOCAL
  //        Type: CALCULAT_NAME
  /**
   * Attribute missing flag for: LocalCalculatNameAlllllll
   **/
  public char LocalCalculatNameAlllllll_AS;
  /**
   * Attribute for: LocalCalculatNameAlllllll
   * Domain: Text
   * Length: 200
   * Varying Length: N
   **/
  public String LocalCalculatNameAlllllll;
  // Entity View: LOCAL_VIR_1
  //        Type: IEF_SUPPLIED
  /**
   * Attribute missing flag for: LocalVir1IefSuppliedResult
   **/
  public char LocalVir1IefSuppliedResult_AS;
  /**
   * Attribute for: LocalVir1IefSuppliedResult
   * Domain: Number
   * Length: 8
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public int LocalVir1IefSuppliedResult;
  // Entity View: LOCAL_VIR_2
  //        Type: IEF_SUPPLIED
  /**
   * Attribute missing flag for: LocalVir2IefSuppliedResult
   **/
  public char LocalVir2IefSuppliedResult_AS;
  /**
   * Attribute for: LocalVir2IefSuppliedResult
   * Domain: Number
   * Length: 8
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public int LocalVir2IefSuppliedResult;
  /**
   * Default Constructor
   **/
  
  public EXPERT_LA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public EXPERT_LA(EXPERT_LA orig)
  {
    LocalFlagIefSuppliedSelectChar_AS = orig.LocalFlagIefSuppliedSelectChar_AS;
    LocalFlagIefSuppliedSelectChar = orig.LocalFlagIefSuppliedSelectChar;
    LocalCalculatNameAlllllll_AS = orig.LocalCalculatNameAlllllll_AS;
    LocalCalculatNameAlllllll = orig.LocalCalculatNameAlllllll;
    LocalVir1IefSuppliedResult_AS = orig.LocalVir1IefSuppliedResult_AS;
    LocalVir1IefSuppliedResult = orig.LocalVir1IefSuppliedResult;
    LocalVir2IefSuppliedResult_AS = orig.LocalVir2IefSuppliedResult_AS;
    LocalVir2IefSuppliedResult = orig.LocalVir2IefSuppliedResult;
  }
  /**
   * Static instance creator function
   **/
  
  public static EXPERT_LA getInstance()
  {
    return new EXPERT_LA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new EXPERT_LA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    LocalFlagIefSuppliedSelectChar_AS = ' ';
    LocalFlagIefSuppliedSelectChar = " ";
    LocalCalculatNameAlllllll_AS = ' ';
    LocalCalculatNameAlllllll = 
"                                                                                                                                                                                                        "
      ;
    LocalVir1IefSuppliedResult_AS = ' ';
    LocalVir1IefSuppliedResult = 0;
    LocalVir2IefSuppliedResult_AS = ' ';
    LocalVir2IefSuppliedResult = 0;
  }
}
