package calculat;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2017 CA Technologies. All rights reserved.
//
//    Name: CALCULAT_WIN                     Date: 2017/04/09
//    Target OS:   JVM                       Time: 22:59:15
//    Target DBMS: JDBC                      User: mansour
//    Access Method: JDBC           
//
//    Generation options:
//    Debug trace option selected
//    Data modeling constraint enforcement not selected
//    Optimized import view initialization not selected
//    Enforce default values with DBMS not selected
//    Init unspecified optional fields to NULL not selected
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;

import com.ca.gen.abrt.*;
import com.ca.gen.abrt.functions.*;
import com.ca.gen.abrt.cascade.*;
import com.ca.gen.abrt.trace.*;
import com.ca.gen.exits.common.*;
import com.ca.gen.odc.*;

public class HOME extends ABBase
{
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // IMPORT VIEW CLASS VARIABLE
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  HOME_IA w_ia;
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // EXPORT VIEW CLASS VARIABLE
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  HOME_OA w_oa;
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // START OF EXIT STATES
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  public final static int ex_ReturnBackToExpertAmaty001 = 238026769;
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // MISC DECLARATIONS AND PROTOTYPES 
  //    FOLLOW AS NEEDED:             
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  boolean func_0022020097_esc_flag;
  boolean func_0417333248_esc_flag;
  boolean func_0417333249_esc_flag;
  boolean func_0417333250_esc_flag;
  boolean func_0417333251_esc_flag;
  boolean func_0417333252_esc_flag;
  PadView padview[] = new PadView [24];
  int trace_ret_code;
  PadText padtext[] = initPadText();
  public PadText [] initPadText()
  {
    PadText [] result = new PadText [PADTEXT_SIZE];
    result[0] = PadText.getInstance(   0,"+->   CALCULAT_WIN                      04/09/2017  22:59");
    result[1] = PadText.getInstance(   0,"!       IMPORTS:");
    result[2] = PadText.getInstance(   0,"!         Work View import_result ief_supplied (Transient, Optional, Import only)");
    result[3] = PadText.getInstance(   0,"!           result");
    result[4] = PadText.getInstance(   0,"!         Work View import_n2nd ief_supplied (Transient, Optional, Import only)");
    result[5] = PadText.getInstance(   0,"!           number2");
    result[6] = PadText.getInstance(   0,"!         Work View import_n1 ief_supplied (Transient, Optional, Import only)");
    result[7] = PadText.getInstance(   0,"!           number1st");
    result[8] = PadText.getInstance(   0,"!       EXPORTS:");
    result[9] = PadText.getInstance(   0,"!         Work View import_amaty_list amaty (Transient, Export only)");
    result[10] = PadText.getInstance(   0,"!           drop_list1");
    result[11] = PadText.getInstance(   0,"!         Work View export_result ief_supplied (Transient, Export only)");
    result[12] = PadText.getInstance(   0,"!           result");
    result[13] = PadText.getInstance(   0,"!         Work View export_n2nd ief_supplied (Transient, Export only)");
    result[14] = PadText.getInstance(   0,"!           number2");
    result[15] = PadText.getInstance(   0,"!         Work View export_n1 ief_supplied (Transient, Export only)");
    result[16] = PadText.getInstance(   0,"!           number1st");
    result[17] = PadText.getInstance(   0,"!");
    result[18] = PadText.getInstance(   0,"!     PROCEDURE STATEMENTS");
    result[19] = PadText.getInstance(   0,"!");
    result[20] = PadText.getInstance(   1,"!  MOVE import_result ief_supplied TO export_result ief_supplied");
    result[21] = PadText.getInstance(   0,"+---");
    result[22] = PadText.getInstance(   0," ");
    result[23] = PadText.getInstance(   0,"+->   EVENT:  CALCULAT_NA_PB_CLICK            ");
    result[24] = PadText.getInstance(   2,
      "!  SET export_result ief_supplied result TO export_n1 ief_supplied number1st + export_n2nd ief_supplied number2 ");
    result[25] = PadText.getInstance(   0,"+---");
    result[26] = PadText.getInstance(   0," ");
    result[27] = PadText.getInstance(   0,"+->   EVENT:  CALCULAT_NA_PB_CLEAR_CLICK      ");
    result[28] = PadText.getInstance(   3,"!  SET export_n1 ief_supplied number1st TO 0 ");
    result[29] = PadText.getInstance(   4,"!  SET export_n2nd ief_supplied number2 TO 0 ");
    result[30] = PadText.getInstance(   5,"!  SET export_result ief_supplied result TO 0 ");
    result[31] = PadText.getInstance(   0,"+---");
    result[32] = PadText.getInstance(   0," ");
    result[33] = PadText.getInstance(   0,"+->   EVENT:  CALCULAT_MIN_PB_CLICK           ");
    result[34] = PadText.getInstance(   6,
      "!  SET export_result ief_supplied result TO export_n1 ief_supplied number1st - export_n2nd ief_supplied number2 ");
    result[35] = PadText.getInstance(   0,"+---");
    result[36] = PadText.getInstance(   0," ");
    result[37] = PadText.getInstance(   0,"+->   EVENT:  CALCULAT_WI_PB_MULTIP_CLICK     ");
    result[38] = PadText.getInstance(   7,
      "!  SET export_result ief_supplied result TO export_n1 ief_supplied number1st * export_n2nd ief_supplied number2 ");
    result[39] = PadText.getInstance(   0,"+---");
    result[40] = PadText.getInstance(   0," ");
    result[41] = PadText.getInstance(   0,"+->   EVENT:  CALCULAT_WI_PB_AMATY_CLICK      ");
    result[42] = PadText.getInstance(   8,"!  EXIT STATE IS return_back_to_expert_amaty");
    result[43] = PadText.getInstance(   0,"+---");
    result[44] = PadText.getInstance(PadText.LASTLINE,"************************* BOTTOM OF DATA *************************");
    return result;
  }
  final static int PADTEXT_SIZE = 45;
  //       +->   CALCULAT_WIN                      04/09/2017  22:59
  //       !       IMPORTS:
  //       !         Work View import_result ief_supplied (Transient, Optional, Import only)
  //       !           result
  //       !         Work View import_n2nd ief_supplied (Transient, Optional, Import only)
  //       !           number2
  //       !         Work View import_n1 ief_supplied (Transient, Optional, Import only)
  //       !           number1st
  //       !       EXPORTS:
  //       !         Work View import_amaty_list amaty (Transient, Export only)
  //       !           drop_list1
  //       !         Work View export_result ief_supplied (Transient, Export only)
  //       !           result
  //       !         Work View export_n2nd ief_supplied (Transient, Export only)
  //       !           number2
  //       !         Work View export_n1 ief_supplied (Transient, Export only)
  //       !           number1st
  //       !
  //       !     PROCEDURE STATEMENTS
  //       !
  //     1 !  MOVE import_result ief_supplied TO export_result ief_supplied
  //       +---
  //        
  //       +->   EVENT:  CALCULAT_NA_PB_CLICK            
  //     2 !  SET export_result ief_supplied result TO export_n1 ief_supplied number1st + export_n2nd ief_supplied number2 
  //       +---
  //        
  //       +->   EVENT:  CALCULAT_NA_PB_CLEAR_CLICK      
  //     3 !  SET export_n1 ief_supplied number1st TO 0 
  //     4 !  SET export_n2nd ief_supplied number2 TO 0 
  //     5 !  SET export_result ief_supplied result TO 0 
  //       +---
  //        
  //       +->   EVENT:  CALCULAT_MIN_PB_CLICK           
  //     6 !  SET export_result ief_supplied result TO export_n1 ief_supplied number1st - export_n2nd ief_supplied number2 
  //       +---
  //        
  //       +->   EVENT:  CALCULAT_WI_PB_MULTIP_CLICK     
  //     7 !  SET export_result ief_supplied result TO export_n1 ief_supplied number1st * export_n2nd ief_supplied number2 
  //       +---
  //        
  //       +->   EVENT:  CALCULAT_WI_PB_AMATY_CLICK      
  //     8 !  EXIT STATE IS return_back_to_expert_amaty
  //       +---
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  //  CONSTRUCTOR FOR THE CLASS       
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  public HOME()
  {
    iefCGenRlse = "CA Gen 8.6";
    ssCopyright = "Copyright (c) 2017 CA Technologies. All rights reserved.";
    iefCGenDate = "2017/04/09";
    iefCGenTime = "22:59:15";
    iefCGenEncy = "9.2.A6";
    iefCGenUserId = "mansour";
    iefCGenModel = "CALCULAT";
    iefCGenSubset = "ALL";
    iefCGenName = "CALCULAT_WIN";
    nestingLevel = 0;
    valChkDeadlockTimeout = false;
    valChkDBError = false;
  }
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // ACTION BLOCK FUNCTION DECLARATIONS 
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  
  public void HOME( Object in_runtime_parm1, 
  	IRuntimePStepContext in_runtime_parm2, 
  	GlobData in_globdata, 
  	HOME_IA import_view, 
  	HOME_OA export_view )
  {
    iefRuntimeParm1 = in_runtime_parm1;
    iefRuntimeParm2 = in_runtime_parm2;
    globdata = in_globdata;
    w_ia = import_view;
    w_oa = export_view;
    _HOME();
  }
  
  private void _HOME()
  {
    
    ++(nestingLevel);
    try {
      f_22020097_init(true);
      f_22020097();
    } catch( ABException e ) {
    } finally {
      --(nestingLevel);
    }
    String last_stmt_num_saved = globdata.getStateData().getLastStatementNumber();
    globdata.getStateData().setLastStatementNumber( "9999999999" );
    try {
      f_0_trace();
    } catch( ABException e ) {
    }
    globdata.getStateData().setLastStatementNumber( last_stmt_num_saved );
  }
  public void f_22020097()
  	throws ABException
  {
    func_0022020097_esc_flag = false;
    globdata.getStateData().setCurrentABId( "0022020097" );
    globdata.getStateData().setCurrentABName( "CALCULAT_WIN" );
    padview_init();
    globdata.getStateData().setLastStatementNumber( "0000000000" );
    f_0_trace();
    globdata.getStateData().setLastStatementNumber( "0000000001" );
    f_0_trace();
    if ( trace_ret_code != 8 )
    {
      w_oa.ExportResultIefSuppliedResult = IntAttr.valueOf(w_ia.ImportResultIefSuppliedResult);
    }
  }
  
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // EVENT HANDLER FUNCTION DECLARATIONS 
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  
  public void home_calculat_na_pb_click01( Object in_runtime_parm1, 
  	IRuntimePStepContext in_runtime_parm2, 
  	GlobData in_globdata, 
  	HOME_IA import_view, 
  	HOME_OA export_view )
  {
    iefRuntimeParm1 = in_runtime_parm1;
    iefRuntimeParm2 = in_runtime_parm2;
    globdata = in_globdata;
    w_ia = import_view;
    w_oa = export_view;
    _home_calculat_na_pb_click01();
  }
  
  private void _home_calculat_na_pb_click01()
  {
    try {
      
      f_22020097_init(false);
      func_0022020097_esc_flag = false;
      func_0417333248_esc_flag = false;
      globdata.getStateData().setCurrentABId( "0022020097" );
      globdata.getStateData().setCurrentABName( "CALCULAT_NA_PB_CLICK" );
      globdata.getStateData().setCurrentEventType( "Click" );
      padview_init();
      globdata.getStateData().setLastStatementNumber( "0000000000" );
      f_0_trace();
      globdata.getStateData().setLastStatementNumber( "0000000002" );
      f_0_trace();
      if ( trace_ret_code != 8 )
      {
        w_oa.ExportResultIefSuppliedResult = IntAttr.valueOf((int)TIRD2DEC.TIRD2DC1(((double) w_oa.ExportN1IefSuppliedNumber1st + (
          double) w_oa.ExportN2ndIefSuppliedNumber2), 0, TIRD2DEC.ROUND_NONE, 8));
      }
    } catch( ABException e ) {
    }
    try {
      
      String last_stmt_num_saved = globdata.getStateData().getLastStatementNumber();
      globdata.getStateData().setLastStatementNumber( "9999999999" );
      f_0_trace();
      globdata.getStateData().setLastStatementNumber( last_stmt_num_saved );
    } catch( ABException e ) {
    }
    return;
  }
  
  public void home_calculat_na_pb_clear_cli02( Object in_runtime_parm1, 
  	IRuntimePStepContext in_runtime_parm2, 
  	GlobData in_globdata, 
  	HOME_IA import_view, 
  	HOME_OA export_view )
  {
    iefRuntimeParm1 = in_runtime_parm1;
    iefRuntimeParm2 = in_runtime_parm2;
    globdata = in_globdata;
    w_ia = import_view;
    w_oa = export_view;
    _home_calculat_na_pb_clear_cli02();
  }
  
  private void _home_calculat_na_pb_clear_cli02()
  {
    try {
      
      f_22020097_init(false);
      func_0022020097_esc_flag = false;
      func_0417333249_esc_flag = false;
      globdata.getStateData().setCurrentABId( "0022020097" );
      globdata.getStateData().setCurrentABName( "CALCULAT_NA_PB_CLEAR_CLICK" );
      globdata.getStateData().setCurrentEventType( "Click" );
      padview_init();
      globdata.getStateData().setLastStatementNumber( "0000000000" );
      f_0_trace();
      globdata.getStateData().setLastStatementNumber( "0000000003" );
      f_0_trace();
      if ( trace_ret_code != 8 )
      {
        w_oa.ExportN1IefSuppliedNumber1st = IntAttr.valueOf((int)TIRD2DEC.TIRD2DC1(0, 0, TIRD2DEC.ROUND_NONE, 8));
      }
      globdata.getStateData().setLastStatementNumber( "0000000004" );
      f_0_trace();
      if ( trace_ret_code != 8 )
      {
        w_oa.ExportN2ndIefSuppliedNumber2 = IntAttr.valueOf((int)TIRD2DEC.TIRD2DC1(0, 0, TIRD2DEC.ROUND_NONE, 5));
      }
      globdata.getStateData().setLastStatementNumber( "0000000005" );
      f_0_trace();
      if ( trace_ret_code != 8 )
      {
        w_oa.ExportResultIefSuppliedResult = IntAttr.valueOf((int)TIRD2DEC.TIRD2DC1(0, 0, TIRD2DEC.ROUND_NONE, 8));
      }
    } catch( ABException e ) {
    }
    try {
      
      String last_stmt_num_saved = globdata.getStateData().getLastStatementNumber();
      globdata.getStateData().setLastStatementNumber( "9999999999" );
      f_0_trace();
      globdata.getStateData().setLastStatementNumber( last_stmt_num_saved );
    } catch( ABException e ) {
    }
    return;
  }
  
  public void home_calculat_min_pb_click03( Object in_runtime_parm1, 
  	IRuntimePStepContext in_runtime_parm2, 
  	GlobData in_globdata, 
  	HOME_IA import_view, 
  	HOME_OA export_view )
  {
    iefRuntimeParm1 = in_runtime_parm1;
    iefRuntimeParm2 = in_runtime_parm2;
    globdata = in_globdata;
    w_ia = import_view;
    w_oa = export_view;
    _home_calculat_min_pb_click03();
  }
  
  private void _home_calculat_min_pb_click03()
  {
    try {
      
      f_22020097_init(false);
      func_0022020097_esc_flag = false;
      func_0417333250_esc_flag = false;
      globdata.getStateData().setCurrentABId( "0022020097" );
      globdata.getStateData().setCurrentABName( "CALCULAT_MIN_PB_CLICK" );
      globdata.getStateData().setCurrentEventType( "Click" );
      padview_init();
      globdata.getStateData().setLastStatementNumber( "0000000000" );
      f_0_trace();
      globdata.getStateData().setLastStatementNumber( "0000000006" );
      f_0_trace();
      if ( trace_ret_code != 8 )
      {
        w_oa.ExportResultIefSuppliedResult = IntAttr.valueOf((int)TIRD2DEC.TIRD2DC1(((double) w_oa.ExportN1IefSuppliedNumber1st - (
          double) w_oa.ExportN2ndIefSuppliedNumber2), 0, TIRD2DEC.ROUND_NONE, 8));
      }
    } catch( ABException e ) {
    }
    try {
      
      String last_stmt_num_saved = globdata.getStateData().getLastStatementNumber();
      globdata.getStateData().setLastStatementNumber( "9999999999" );
      f_0_trace();
      globdata.getStateData().setLastStatementNumber( last_stmt_num_saved );
    } catch( ABException e ) {
    }
    return;
  }
  
  public void home_calculat_wi_pb_multip_cl04( Object in_runtime_parm1, 
  	IRuntimePStepContext in_runtime_parm2, 
  	GlobData in_globdata, 
  	HOME_IA import_view, 
  	HOME_OA export_view )
  {
    iefRuntimeParm1 = in_runtime_parm1;
    iefRuntimeParm2 = in_runtime_parm2;
    globdata = in_globdata;
    w_ia = import_view;
    w_oa = export_view;
    _home_calculat_wi_pb_multip_cl04();
  }
  
  private void _home_calculat_wi_pb_multip_cl04()
  {
    try {
      
      f_22020097_init(false);
      func_0022020097_esc_flag = false;
      func_0417333251_esc_flag = false;
      globdata.getStateData().setCurrentABId( "0022020097" );
      globdata.getStateData().setCurrentABName( "CALCULAT_WI_PB_MULTIP_CLICK" );
      globdata.getStateData().setCurrentEventType( "Click" );
      padview_init();
      globdata.getStateData().setLastStatementNumber( "0000000000" );
      f_0_trace();
      globdata.getStateData().setLastStatementNumber( "0000000007" );
      f_0_trace();
      if ( trace_ret_code != 8 )
      {
        w_oa.ExportResultIefSuppliedResult = IntAttr.valueOf((int)TIRD2DEC.TIRD2DC1(((double) w_oa.ExportN1IefSuppliedNumber1st * (
          double) w_oa.ExportN2ndIefSuppliedNumber2), 0, TIRD2DEC.ROUND_NONE, 8));
      }
    } catch( ABException e ) {
    }
    try {
      
      String last_stmt_num_saved = globdata.getStateData().getLastStatementNumber();
      globdata.getStateData().setLastStatementNumber( "9999999999" );
      f_0_trace();
      globdata.getStateData().setLastStatementNumber( last_stmt_num_saved );
    } catch( ABException e ) {
    }
    return;
  }
  
  public void home_calculat_wi_pb_amaty_cli05( Object in_runtime_parm1, 
  	IRuntimePStepContext in_runtime_parm2, 
  	GlobData in_globdata, 
  	HOME_IA import_view, 
  	HOME_OA export_view )
  {
    iefRuntimeParm1 = in_runtime_parm1;
    iefRuntimeParm2 = in_runtime_parm2;
    globdata = in_globdata;
    w_ia = import_view;
    w_oa = export_view;
    _home_calculat_wi_pb_amaty_cli05();
  }
  
  private void _home_calculat_wi_pb_amaty_cli05()
  {
    try {
      
      f_22020097_init(false);
      func_0022020097_esc_flag = false;
      func_0417333252_esc_flag = false;
      globdata.getStateData().setCurrentABId( "0022020097" );
      globdata.getStateData().setCurrentABName( "CALCULAT_WI_PB_AMATY_CLICK" );
      globdata.getStateData().setCurrentEventType( "Click" );
      padview_init();
      globdata.getStateData().setLastStatementNumber( "0000000000" );
      f_0_trace();
      globdata.getStateData().setLastStatementNumber( "0000000008" );
      f_0_trace();
      if ( trace_ret_code != 8 )
      {
        globdata.getStateData().setExitState( ex_ReturnBackToExpertAmaty001 );
        globdata.getStateData().setExitInfoMsg( " " );
        globdata.getErrorData().setRollbackRequested( ' ' );
        globdata.getStateData().setExitMsgType( 'N' );
      }
    } catch( ABException e ) {
    }
    try {
      
      String last_stmt_num_saved = globdata.getStateData().getLastStatementNumber();
      globdata.getStateData().setLastStatementNumber( "9999999999" );
      f_0_trace();
      globdata.getStateData().setLastStatementNumber( last_stmt_num_saved );
    } catch( ABException e ) {
    }
    return;
  }
  
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // SUBORDINATE FUNCTIONS
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // INITIALIZATION UTILITY FUNCTIONS 
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  
  public void f_22020097_init(boolean doall)
  	throws ABException
  {
    if ( nestingLevel < 2 )
    {
    }
    if ( doall )
    {
      w_oa.ImportAmatyListAmatyDropList1 = " ";
      w_oa.ExportResultIefSuppliedResult = 0;
      w_oa.ExportN2ndIefSuppliedNumber2 = 0;
      w_oa.ExportN1IefSuppliedNumber1st = 0;
    }
    if ( doall )
    {
    }
  }
  
  public void f_0_trace()
  	throws ABException
  {
    trace_ret_code = TIRTRCE.TIRTRCE(iefRuntimeParm1, iefRuntimeParm2, globdata, padtext, padview);
    if ( trace_ret_code == 20 )
    {
      throw new ABException();
    }
  }
  
  public void padview_init()
  {
padview[0] = PadView.getInstance("IMPORT                          ", 0, 0, 0, (short)1, PadView.VT_BASE, PadView.DT_NONE, w_ia, 
      "w_ia");
    padview[1] = PadView.getInstance("IMPORT_RESULT                   ", 0, 0, 0, (short)2, PadView.VT_VIEW, PadView.DT_NONE, w_ia, 
      null);
    padview[2] = PadView.getInstance("IEF_SUPPLIED                    ", 0, 0, 0, (short)3, PadView.VT_ENTITY, PadView.DT_NONE, w_ia,
       null);
    padview[3] = PadView.getInstance("RESULT                          ", 8, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_NUMERIC,
       w_ia, "ImportResultIefSuppliedResult");
    padview[4] = PadView.getInstance("IMPORT_N2ND                     ", 0, 0, 0, (short)2, PadView.VT_VIEW, PadView.DT_NONE, w_ia, 
      null);
    padview[5] = PadView.getInstance("IEF_SUPPLIED                    ", 0, 0, 0, (short)3, PadView.VT_ENTITY, PadView.DT_NONE, w_ia,
       null);
    padview[6] = PadView.getInstance("NUMBER2                         ", 5, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_NUMERIC,
       w_ia, "ImportN2ndIefSuppliedNumber2");
    padview[7] = PadView.getInstance("IMPORT_N1                       ", 0, 0, 0, (short)2, PadView.VT_VIEW, PadView.DT_NONE, w_ia, 
      null);
    padview[8] = PadView.getInstance("IEF_SUPPLIED                    ", 0, 0, 0, (short)3, PadView.VT_ENTITY, PadView.DT_NONE, w_ia,
       null);
    padview[9] = PadView.getInstance("NUMBER1ST                       ", 8, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_NUMERIC,
       w_ia, "ImportN1IefSuppliedNumber1st");
    padview[10] = PadView.getInstance("EXPORT                          ", 0, 0, 0, (short)1, PadView.VT_BASE, PadView.DT_NONE, w_oa, 
      "w_oa");
    padview[11] = PadView.getInstance("IMPORT_AMATY_LIST               ", 0, 0, 0, (short)2, PadView.VT_VIEW, PadView.DT_NONE, w_oa, 
      null);
    padview[12] = PadView.getInstance("AMATY                           ", 0, 0, 0, (short)3, PadView.VT_ENTITY, PadView.DT_NONE, 
      w_oa, null);
    padview[13] = PadView.getInstance("DROP_LIST1                      ", 1, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_TEXT, 
      w_oa, "ImportAmatyListAmatyDropList1");
    padview[14] = PadView.getInstance("EXPORT_RESULT                   ", 0, 0, 0, (short)2, PadView.VT_VIEW, PadView.DT_NONE, w_oa, 
      null);
    padview[15] = PadView.getInstance("IEF_SUPPLIED                    ", 0, 0, 0, (short)3, PadView.VT_ENTITY, PadView.DT_NONE, 
      w_oa, null);
    padview[16] = PadView.getInstance("RESULT                          ", 8, 0, 0, (short)3, PadView.VT_PREDICATE, 
      PadView.DT_NUMERIC, w_oa, "ExportResultIefSuppliedResult");
    padview[17] = PadView.getInstance("EXPORT_N2ND                     ", 0, 0, 0, (short)2, PadView.VT_VIEW, PadView.DT_NONE, w_oa, 
      null);
    padview[18] = PadView.getInstance("IEF_SUPPLIED                    ", 0, 0, 0, (short)3, PadView.VT_ENTITY, PadView.DT_NONE, 
      w_oa, null);
    padview[19] = PadView.getInstance("NUMBER2                         ", 5, 0, 0, (short)3, PadView.VT_PREDICATE, 
      PadView.DT_NUMERIC, w_oa, "ExportN2ndIefSuppliedNumber2");
    padview[20] = PadView.getInstance("EXPORT_N1                       ", 0, 0, 0, (short)2, PadView.VT_VIEW, PadView.DT_NONE, w_oa, 
      null);
    padview[21] = PadView.getInstance("IEF_SUPPLIED                    ", 0, 0, 0, (short)3, PadView.VT_ENTITY, PadView.DT_NONE, 
      w_oa, null);
    padview[22] = PadView.getInstance("NUMBER1ST                       ", 8, 0, 0, (short)3, PadView.VT_PREDICATE, 
      PadView.DT_NUMERIC, w_oa, "ExportN1IefSuppliedNumber1st");
    padview[23] = PadView.getInstance("******** BOTTOM OF DATA ********", 0, 0, 0, (short)0, PadView.VT_END, PadView.DT_NONE, w_oa, 
      null);
  }
}// end class

